/**
 * 그림이 있는 물건.
 *
 * 파일 이름이 곧 아이템 id 이고, 분류가 곧 폴더다.
 * 새 그림이 들어오면 public/assets/items/<분류>/<id>.webp 에 넣고
 * 아래 목록에 한 줄만 더하면 도감·상점·방·가방이 전부 알아서 쓴다.
 *
 * 경로를 여기서 만들지 않는 이유: 분류는 아이템 표가 알고 있다.
 * 두 곳에 적어두면 언젠가 어긋난다. (조립은 catalog.ts 에서 한다)
 *
 * 아직 그림이 없는 물건은 이모지로, 이모지도 없으면 분류 실루엣으로 그린다.
 */
const BASE = '/assets/items'
/** 도감 격자에서 쓰는 작은 그림 (npm run assets:thumbs) */
const THUMB_BASE = '/assets/thumbs'

/** 파일이 들어 있는 분류별 폴더 */
const FOLDER: Record<string, string> = {
  FURNITURE: 'furniture',
  LIGHTING: 'lighting',
  PLANT: 'plants',
  RUG: 'rugs',
  WALL: 'wall',
  LITTLE_THING: 'little_things',
  KITCHEN: 'kitchen',
  FOOD: 'food',
  BOOK: 'books',
  HOBBY: 'hobby',
  TECH: 'tech',
  OUTDOOR: 'outdoor',
  MAGIC: 'magic',
  TROPHY: 'trophies',
  MATERIAL: 'materials',
}

const WITH_ART = [
  'abstract_poster',
  'acrylic_chair',
  'apple_basket',
  'art_box',
  'baby_breath',
  'basil_pot',
  'big_monstera',
  'board_game',
  'bud_lamp',
  'bunny_cactus',
  'cafe_table',
  'cake_slice',
  'candle_light',
  'cat_cushion',
  'cat_lamp',
  'cat_paw_rug',
  'cereal_bowl',
  'chalk_bag',
  'check_blanket',
  'check_rug',
  'check_sofa',
  'checklist_notebook',
  'clear_umbrella',
  'cloud_bed',
  'cloud_blanket',
  'cloud_keyring',
  'cloud_light',
  'cloud_mobile',
  'cloud_piece',
  'clover',
  'clover_bottle',
  'coat_rack',
  'coffee_cup',
  'controller',
  'cook_book',
  'cookie_plate',
  'cork_board',
  'craft_cabinet',
  'cream_bed',
  'cream_clock',
  'cream_drawer',
  'cream_rug',
  'croissant',
  'cutting_board',
  'dawn_crystal',
  'dawn_lamp',
  'daybed',
  'desk_calendar',
  'drawer_nightstand',
  'dream_piece',
  'duo_table',
  'easel',
  'eco_bag',
  'entry_bench',
  'fairy_lights',
  'fashion_magazine',
  'film_roll',
  'firefly_jar',
  'floor_chair',
  'floor_lamp',
  'flower_plate',
  'flower_poster',
  'flower_rug',
  'fountain_pen',
  'friend_photo',
  'frying_pan',
  'full_shelf',
  'garland',
  'glass_cabinet',
  'glass_teacup',
  'glasses_case',
  'green_stand',
  'guitar',
  'hand_mirror',
  'handheld',
  'headphones_c',
  'herb_pot',
  'home_cafe_cart',
  'instant_camera',
  'jam_toast',
  'jewel_box',
  'keyboard',
  'kitchen_shelf',
  'knitting_basket',
  'landscape_poster',
  'latte_cup',
  'laundry_basket',
  'lavender_pot',
  'lemonade',
  'letter',
  'little_moon',
  'low_shelf',
  'lucky_keyring_c',
  'm_cloth',
  'm_glass',
  'm_leaf',
  'm_metal',
  'm_paper',
  'm_petal',
  'm_stone',
  'm_wood',
  'matchbox',
  'milk_bottle',
  'mini_cactus',
  'mini_piano',
  'mini_shelf',
  'monitor',
  'moon_globe',
  'moon_keyring_c',
  'moon_light',
  'moon_poster',
  'moon_ticket_c',
  'moondust_jar',
  'mouse',
  'movie_poster',
  'mushroom_lamp',
  'mushroom_pot',
  'mushroom_rug',
  'mushroom_stool',
  'my_mug',
  'neon_star',
  'night_flower',
  'night_ticket_c',
  'old_map',
  'old_picture_book',
  'olive_tree',
  'oven_mitt',
  'palette',
  'pancake',
  'paper_lantern',
  'pencil_case',
  'pencil_cup',
  'persian_rug',
  'picnic_mat',
  'pink_beanbag',
  'pink_cloud_rug',
  'pink_glass_lamp',
  'pink_sofa',
  'pink_tulip',
  'plant_book',
  'poem_book',
  'polaroid_wall',
  'postcards',
  'pothos',
  'puzzle_box',
  'raindrop_crystal',
  'raindrop_light',
  'raindrop_rug',
  'rainy_candle',
  'rattan_basket',
  'rattan_chair',
  'rattan_storage',
  'reading_chair',
  'reading_light',
  'record',
  'record_cabinet',
  'rose_vase',
  'rosemary_pot',
  'round_stool',
  'round_vanity',
  'rubber_tree',
  'sage_cabinet',
  'sage_chair',
  'sage_rug',
  'secret_diary',
  'shiny_pebble',
  'shoe_cabinet',
  'sketchbook',
  'sleeping_star',
  'sleepy_bear_cushion',
  'small_bin',
  'small_blanket',
  'small_candle',
  'small_comb',
  'small_frame',
  'small_hanger',
  'small_laptop',
  'small_monstera',
  'small_nightstand',
  'small_notebook',
  'small_pot',
  'small_pouch',
  'small_radio',
  'small_tumbler',
  'small_umbrella',
  'sneakers_c',
  'speaker',
  'sprout_jar',
  'star_book',
  'star_cushion',
  'star_lamp',
  'star_mobile',
  'star_music_box',
  'star_piece',
  'star_projector',
  'star_side_table',
  'stardust_jar',
  'sticky_notes',
  'strawberry_cake',
  'strawberry_pack',
  'succulent',
  'sunflower',
  'sunlight_rug',
  'sunset_crystal',
  'sunset_lamp',
  't_dragon',
  't_golden_broom',
  't_golden_pen',
  't_hundred_stars',
  't_shiny_palette',
  't_shoe_trophy',
  'tablet',
  'tangerine_basket',
  'tea_table',
  'thick_essay',
  'toast_butter',
  'toast_plate',
  'travel_magazine',
  'trolley',
  'turntable',
  'umbrella_stand',
  'unfinished_novel',
  'vanity',
  'vintage_alarm',
  'vintage_camera',
  'vintage_lamp',
  'vintage_side_table',
  'vintage_sofa',
  'wall_clock',
  'wall_mirror',
  'warm_tea',
  'water_bottle',
  'white_daisy',
  'white_rug',
  'wildflowers',
  'window_bench',
  'window_desk',
  'window_ivy',
  'window_ledge',
  'wood_bed',
  'wood_bench',
  'wood_desk',
  'wood_tray',
  'work_chair',
  'yarn',
  'yellow_cushion',
  'yellow_tulip',
  'yoga_mat',
] as const

/**
 * 시트에 없어서 직접 그린 것.
 *
 * 원본은 assets/drawn/<id>.svg 다. SVG 를 고치고 `npm run assets:draw` 를
 * 다시 돌리면 게임 안 그림도 따라 바뀐다.
 *
 * 이모지로 그리던 자리를 없애려고 그렸다. 이모지는 폰마다 모양이 달라서
 * 어떤 기기에서는 도감 한 칸만 결이 다르게 보인다.
 */
const DRAWN = [
  'beanbag',
  'constellation_rug',
  'mini_table',
  'secret_drawer',
  'small_cabinet',
  'star_pot',
  't_adventure_book',
  't_heart_bottle',
  't_moon_shard',
  't_thousand_stars',
  't_wood_star',
] as const

/** 손으로 그린 것 (도감에서 따로 표시하지는 않는다 — 그림은 그림이다) */
export const DRAWN_BY_HAND = new Set<string>(DRAWN)

/** 그림이 있는지 */
export const HAS_ART = new Set<string>([...WITH_ART, ...DRAWN])

/** 분류를 알아야 경로가 나온다 */
export function artPath(itemId: string, category: string): string | undefined {
  if (!HAS_ART.has(itemId)) return undefined
  return `${BASE}/${FOLDER[category] ?? 'misc'}/${itemId}.webp`
}

/**
 * 작게 보여줄 때 쓰는 그림.
 *
 * 도감 한 칸은 폰에서 32~56px 다. 240칸을 훑는데 320px 짜리를 다 받으면
 * 필요 없는 데이터를 몇 배로 받는다. 크게 보는 자리(방·상세)는 원본을 쓴다.
 */
export function thumbPath(itemId: string, category: string): string | undefined {
  if (!HAS_ART.has(itemId)) return undefined
  return `${THUMB_BASE}/${FOLDER[category] ?? 'misc'}/${itemId}.webp`
}
