/**
 * 그림이 있는 물건.
 *
 * 파일 이름이 곧 아이템 id 다. 새 그림이 들어오면
 * public/assets/collection/ 에 <id>.webp 를 넣고 여기에 한 줄만 더하면
 * 도감·상점·방·가방이 전부 알아서 쓴다.
 *
 * 아직 그림이 없는 물건은 이모지로, 이모지도 없으면 분류 실루엣으로 그린다.
 */
const BASE = '/assets/collection'

const WITH_ART = [
  'basil_pot',
  'big_monstera',
  'bunny_cactus',
  'cafe_table',
  'cat_cushion',
  'cereal_bowl',
  'clear_umbrella',
  'cloud_bed',
  'cloud_light',
  'cloud_mobile',
  'cloud_piece',
  'clover_bottle',
  'cream_bed',
  'cream_drawer',
  'cream_rug',
  'croissant',
  'dawn_crystal',
  'daybed',
  'drawer_nightstand',
  'dream_piece',
  'fairy_lights',
  'firefly_jar',
  'floor_lamp',
  'flower_plate',
  'flower_poster',
  'flower_rug',
  'glass_teacup',
  'green_stand',
  'instant_camera',
  'jam_toast',
  'landscape_poster',
  'latte_cup',
  'laundry_basket',
  'lemonade',
  'little_moon',
  'low_shelf',
  'm_cloth',
  'm_glass',
  'm_leaf',
  'm_metal',
  'm_paper',
  'm_petal',
  'm_stone',
  'm_wood',
  'mini_cactus',
  'mini_shelf',
  'moon_globe',
  'moon_light',
  'moon_poster',
  'moon_ticket_c',
  'moondust_jar',
  'mushroom_lamp',
  'mushroom_stool',
  'my_mug',
  'night_ticket_c',
  'olive_tree',
  'pink_beanbag',
  'pink_cloud_rug',
  'pink_glass_lamp',
  'pink_sofa',
  'pink_tulip',
  'pothos',
  'raindrop_crystal',
  'raindrop_rug',
  'rainy_candle',
  'rattan_basket',
  'rattan_chair',
  'rattan_storage',
  'reading_chair',
  'reading_light',
  'round_stool',
  'rubber_tree',
  'sage_chair',
  'sage_rug',
  'shiny_pebble',
  'sleeping_star',
  'sleepy_bear_cushion',
  'small_candle',
  'small_hanger',
  'small_monstera',
  'small_pot',
  'small_radio',
  'small_tumbler',
  'small_umbrella',
  'star_lamp',
  'star_mobile',
  'star_music_box',
  'star_piece',
  'stardust_jar',
  'strawberry_cake',
  'succulent',
  'sunlight_rug',
  'sunset_crystal',
  't_dragon',
  't_golden_broom',
  't_golden_pen',
  't_hundred_stars',
  't_shiny_palette',
  't_shoe_trophy',
  'tea_table',
  'umbrella_stand',
  'vintage_alarm',
  'vintage_lamp',
  'vintage_side_table',
  'vintage_sofa',
  'wall_clock',
  'water_bottle',
  'white_daisy',
  'window_desk',
  'window_ivy',
  'wood_bed',
  'wood_desk',
  'wood_tray',
  'work_chair',
] as const

export const COLLECTION_ART: Record<string, string> = Object.fromEntries(
  WITH_ART.map((id) => [id, `${BASE}/${id}.webp`]),
)

export function artFor(itemId: string): string | undefined {
  return COLLECTION_ART[itemId]
}
