import type { AreaDef, BattleDef, ClassDef, ItemDef } from '@/types'

/**
 * 이번 업데이트의 모든 밸런스 값이 여기 모여 있다.
 * 숫자를 고칠 일이 생기면 이 파일만 열면 된다.
 *
 * 검·갑옷·성 대신 머그컵·헤드폰·운동화·카페·공원으로 만든다.
 */

// ── 지역 ────────────────────────────────────────────────
export const AREAS: AreaDef[] = [
  {
    id: 'HOME_BASE',
    name: '우리 집',
    icon: '🏠',
    description: '쉬고, 정리하고, 하루를 다시 시작하는 나의 작은 자리.',
    categories: ['LIFE', 'MIND'],
    buffName: '집의 편안함',
    buffLabel: '생활 · 마음 EXP +5%',
    bonuses: { expPctByCategory: { LIFE: 5, MIND: 5 } },
  },
  {
    id: 'CAFE_STREET',
    name: '카페 거리',
    icon: '☕',
    description: '커피 한 잔 놓고 집중이 잘 붙는 거리.',
    categories: ['WORK', 'MIND'],
    buffName: '깊은 집중',
    buffLabel: '일 EXP +10%',
    bonuses: { expPctByCategory: { WORK: 10 } },
  },
  {
    id: 'GREEN_PARK',
    name: '초록 공원',
    icon: '🌳',
    description: '바람이 통하는 곳. 몸을 움직이거나 사람을 만나기 좋다.',
    categories: ['BODY', 'HEART'],
    buffName: '맑은 공기',
    buffLabel: '몸 EXP +10%',
    bonuses: { expPctByCategory: { BODY: 10 } },
  },
  {
    id: 'CREATIVE_DISTRICT',
    name: '창작 골목',
    icon: '🎨',
    description: '뭔가 만들고 싶어지는 동네. 좋은 게 자주 굴러다닌다.',
    categories: ['PLAY', 'MIND'],
    buffName: '영감',
    buffLabel: '놀이 EXP +10% · 귀함 드롭 +3%',
    bonuses: { expPctByCategory: { PLAY: 10 }, rareDropChancePct: 3 },
  },
  {
    id: 'TRAINING_ZONE',
    name: '운동 구역',
    icon: '👟',
    description: '몸 쓰는 일에만 집중하는 공간.',
    categories: ['BODY'],
    buffName: '훈련 모드',
    buffLabel: '몸 보상 +15%',
    bonuses: { rewardPctByCategory: { BODY: 15 } },
  },
  {
    id: 'NIGHT_TOWN',
    name: '밤의 거리',
    icon: '🌙',
    description: '조용해진 도시. 생각을 정리하기 좋은 시간.',
    categories: ['MIND', 'LIFE', 'HEART'],
    buffName: '밤의 고요',
    buffLabel: '마음 EXP +10%',
    bonuses: { expPctByCategory: { MIND: 10 } },
    nightOnly: true,
  },
]

export function findArea(id: string): AreaDef {
  return AREAS.find((a) => a.id === id) ?? AREAS[0]
}

// ── 직업 ────────────────────────────────────────────────
export const CLASSES: ClassDef[] = [
  {
    id: 'PLANNER',
    name: '계획하는 사람',
    icon: '🗓️',
    description: '큰 일을 쪼개서 끝까지 가는 사람.',
    passiveName: '꾸준한 계획',
    passiveLabel: '어려움 퀘스트 EXP +5%',
    bonuses: { hardExpPct: 5 },
  },
  {
    id: 'MAKER',
    name: '만드는 사람',
    icon: '🛠️',
    description: '만들면서 배우는 사람. 좋은 걸 잘 주워온다.',
    passiveName: '좋은 눈',
    passiveLabel: '귀함 이상 드롭 +3%',
    bonuses: { rareDropChancePct: 3 },
  },
  {
    id: 'EXPLORER',
    name: '돌아다니는 사람',
    icon: '🧭',
    description: '어디든 한번 가보는 사람. 주머니가 잘 찬다.',
    passiveName: '기념품',
    // 명세의 "Random Quest reward +10%" 를 지금 구조에 맞게 옮겼다 (README 에 적어둠)
    passiveLabel: '모든 퀘스트 코인 +10%',
    bonuses: { coinPct: 10 },
  },
  {
    id: 'CARETAKER',
    name: '돌보는 사람',
    icon: '🧺',
    description: '나와 주변을 돌보는 사람.',
    passiveName: '따뜻한 손',
    passiveLabel: '생활 · 마음 EXP +3%',
    bonuses: { expPctByCategory: { LIFE: 3, MIND: 3 } },
  },
  {
    id: 'MOVER',
    name: '움직이는 사람',
    icon: '🏃',
    description: '일단 몸을 움직이고 보는 사람.',
    passiveName: '몸이 풀림',
    passiveLabel: '몸 EXP +10%',
    bonuses: { expPctByCategory: { BODY: 10 } },
  },
]

export function findClass(id: string | null): ClassDef | null {
  return CLASSES.find((c) => c.id === id) ?? null
}

// ── 아이템 ──────────────────────────────────────────────
export const ITEMS: ItemDef[] = [
  // COMMON
  {
    id: 'favorite_mug',
    name: '애착 머그컵',
    description: '손에 익은 머그컵. 이걸로 마셔야 생각이 정리된다.',
    type: 'EQUIPMENT',
    rarity: 'COMMON',
    icon: '☕',
    equipSlot: 'CHARM',
    effectLabel: '마음 EXP +3%',
    bonuses: { expPctByCategory: { MIND: 3 } },
    giftTags: ['coffee', 'cozy'],
  },
  {
    id: 'tiny_hair_clip',
    name: '작은 머리핀',
    description: '앞머리를 넘길 때 쓰는 작은 핀. 왠지 운이 좋다.',
    type: 'EQUIPMENT',
    rarity: 'COMMON',
    icon: '🎀',
    equipSlot: 'ACCESSORY',
    effectLabel: '행운 +1',
    bonuses: { luck: 1 },
    giftTags: ['collectible'],
  },
  {
    id: 'cozy_hoodie',
    name: '포근한 후드',
    description: '집에서 제일 많이 입는 후드. 입으면 일단 편하다.',
    type: 'EQUIPMENT',
    rarity: 'COMMON',
    icon: '🧥',
    equipSlot: 'TOP',
    effectLabel: '생활 EXP +3%',
    bonuses: { expPctByCategory: { LIFE: 3 } },
  },
  {
    id: 'daily_sneakers',
    name: '매일 신는 운동화',
    description: '아무 데나 신고 나가는 운동화.',
    type: 'EQUIPMENT',
    rarity: 'COMMON',
    icon: '👟',
    equipSlot: 'SHOES',
    effectLabel: '몸 EXP +3%',
    bonuses: { expPctByCategory: { BODY: 3 } },
  },
  {
    id: 'soft_cap',
    name: '푹신한 모자',
    description: '머리 안 감은 날의 친구.',
    type: 'EQUIPMENT',
    rarity: 'COMMON',
    icon: '🧢',
    equipSlot: 'HEAD',
    effectLabel: '놀이 EXP +2%',
    bonuses: { expPctByCategory: { PLAY: 2 } },
  },
  {
    id: 'comfort_shorts',
    name: '편한 반바지',
    description: '집안일 할 때 제일 편한 반바지.',
    type: 'EQUIPMENT',
    rarity: 'COMMON',
    icon: '🩳',
    equipSlot: 'BOTTOM',
    effectLabel: '생활 EXP +2%',
    bonuses: { expPctByCategory: { LIFE: 2 } },
  },

  // RARE
  {
    id: 'noise_cancelling_headphones',
    name: '노이즈 캔슬링 헤드폰',
    description: '쓰는 순간 세상이 조용해진다.',
    type: 'EQUIPMENT',
    rarity: 'RARE',
    icon: '🎧',
    equipSlot: 'ACCESSORY',
    effectLabel: '일 EXP +5%',
    bonuses: { expPctByCategory: { WORK: 5 } },
  },
  {
    id: 'lucky_sneakers',
    name: '행운의 운동화',
    description: '이걸 신은 날은 이상하게 더 걷게 된다.',
    type: 'EQUIPMENT',
    rarity: 'RARE',
    icon: '✨',
    equipSlot: 'SHOES',
    effectLabel: '몸 EXP +5%',
    bonuses: { expPctByCategory: { BODY: 5 } },
  },
  {
    id: 'adventure_tote',
    name: '모험 가방',
    description: '뭐든 일단 담아오는 가방.',
    type: 'EQUIPMENT',
    rarity: 'RARE',
    icon: '👜',
    equipSlot: 'ACCESSORY',
    effectLabel: '드롭 확률 +2%',
    bonuses: { dropChancePct: 2 },
  },
  {
    id: 'focus_watch',
    name: '집중 시계',
    description: '남은 시간을 보면 이상하게 더 집중된다.',
    type: 'EQUIPMENT',
    rarity: 'RARE',
    icon: '⌚',
    equipSlot: 'ACCESSORY',
    effectLabel: '어려움 퀘스트 EXP +5%',
    bonuses: { hardExpPct: 5 },
  },

  // EPIC
  {
    id: 'lucky_keyring',
    name: '행운의 키링',
    description: '언제 생겼는지 모를 키링. 좋은 일이 자주 따라온다.',
    type: 'EQUIPMENT',
    rarity: 'EPIC',
    icon: '🔑',
    equipSlot: 'CHARM',
    effectLabel: '귀함 이상 드롭 +4%',
    bonuses: { rareDropChancePct: 4 },
  },
  {
    id: 'perfect_work_headset',
    name: '완벽한 작업 헤드셋',
    description: '쓰면 오늘 할 일이 갑자기 할 만해 보인다.',
    type: 'EQUIPMENT',
    rarity: 'EPIC',
    icon: '🎙️',
    equipSlot: 'HEAD',
    effectLabel: '일 EXP +8%',
    bonuses: { expPctByCategory: { WORK: 8 } },
  },

  // LEGENDARY — 구조만 열어두고 실제 드롭은 이번 버전에 없다
  {
    id: 'star_fragment',
    name: '별 조각',
    description: '어느 밤 주머니에 들어와 있던 별 조각.',
    type: 'COLLECTIBLE',
    rarity: 'LEGENDARY',
    icon: '⭐',
    equipSlot: null,
    effectLabel: '아직 쓸 곳이 없다',
    bonuses: {},
    giftTags: ['moon', 'collectible'],
  },

  // MATERIAL — placeholder
  {
    id: 'spare_button',
    name: '여분 단추',
    description: '언젠가 쓸 것 같아서 모아둔 단추.',
    type: 'MATERIAL',
    rarity: 'COMMON',
    icon: '🔘',
    equipSlot: null,
    effectLabel: '아직 쓸 곳이 없다',
    bonuses: {},
    giftTags: ['collectible'],
  },

  // ── 도시에서 얻는 것들 ────────────────────────────────
  // 마시는 것 — 다음 퀘스트 한 번에만 걸린다
  {
    id: 'focus_coffee',
    name: '집중 커피',
    description: 'Mina 가 내려준 커피. 마시면 한동안 딴생각이 안 난다.',
    type: 'CONSUMABLE',
    rarity: 'COMMON',
    icon: '☕',
    equipSlot: null,
    effectLabel: '다음 일 퀘스트 EXP +20%',
    bonuses: {},
    consumable: { category: 'WORK', expPct: 20, uses: 1 },
    giftTags: ['coffee'],
  },
  {
    id: 'rainy_day_tea',
    name: '비 오는 날의 차',
    description: '비 오는 날에만 꺼낸다는 찻잎.',
    type: 'CONSUMABLE',
    rarity: 'RARE',
    icon: '🍵',
    equipSlot: null,
    effectLabel: '다음 마음 퀘스트 EXP +20%',
    bonuses: {},
    consumable: { category: 'MIND', expPct: 20, uses: 1 },
    giftTags: ['coffee', 'cozy'],
  },
  {
    id: 'small_dessert',
    name: '작은 디저트',
    description: '한 입 크기의 케이크. 별거 아닌데 기분이 좋아진다.',
    type: 'CONSUMABLE',
    rarity: 'COMMON',
    icon: '🍰',
    equipSlot: null,
    effectLabel: '다음 퀘스트 EXP +10%',
    bonuses: {},
    consumable: { category: null, expPct: 10, uses: 1 },
    giftTags: ['cozy'],
  },

  // 장비 — 상점과 NPC 의뢰에서 나온다
  {
    id: 'morning_sneakers',
    name: '아침 운동화',
    description: 'Haru 가 신어보라며 준 운동화. 발이 가볍다.',
    type: 'EQUIPMENT',
    rarity: 'RARE',
    icon: '👟',
    equipSlot: 'SHOES',
    effectLabel: '몸 EXP +6%',
    bonuses: { expPctByCategory: { BODY: 6 } },
    giftTags: ['sport'],
  },
  {
    id: 'training_band',
    name: '운동 밴드',
    description: '어디서든 쓸 수 있는 밴드. Rio 가 하나씩 나눠준다.',
    type: 'EQUIPMENT',
    rarity: 'RARE',
    icon: '🎽',
    equipSlot: 'TOP',
    effectLabel: '몸 보상 +8%',
    bonuses: { rewardPctByCategory: { BODY: 8 } },
    giftTags: ['sport'],
  },
  {
    id: 'vintage_ribbon',
    name: '오래된 리본',
    description: 'June 의 가게에서 나온 오래된 리본. 색이 곱게 바랬다.',
    type: 'EQUIPMENT',
    rarity: 'RARE',
    icon: '🎀',
    equipSlot: 'HEAD',
    effectLabel: '놀이 EXP +5%',
    bonuses: { expPctByCategory: { PLAY: 5 } },
    giftTags: ['collectible', 'cozy'],
  },
  {
    id: 'cozy_scarf',
    name: '포근한 목도리',
    description: '목에 두르면 어깨가 저절로 내려간다.',
    type: 'EQUIPMENT',
    rarity: 'RARE',
    icon: '🧣',
    equipSlot: 'ACCESSORY',
    effectLabel: '생활 · 마음 EXP +4%',
    bonuses: { expPctByCategory: { LIFE: 4, MIND: 4 } },
    giftTags: ['cozy'],
  },
  {
    id: 'tiny_sketchbook',
    name: '작은 스케치북',
    description: '주머니에 들어가는 스케치북. Lulu 는 늘 하나씩 가지고 다닌다.',
    type: 'EQUIPMENT',
    rarity: 'RARE',
    icon: '📓',
    equipSlot: 'CHARM',
    effectLabel: '놀이 보상 +8%',
    bonuses: { rewardPctByCategory: { PLAY: 8 } },
    giftTags: ['art', 'book'],
  },
  {
    id: 'green_charm',
    name: '초록 부적',
    description: '공원에서 주운 잎으로 만든 부적.',
    type: 'EQUIPMENT',
    rarity: 'RARE',
    icon: '🍀',
    equipSlot: 'CHARM',
    effectLabel: '행운 +2 · 관계 EXP +4%',
    bonuses: { luck: 2, expPctByCategory: { HEART: 4 } },
    giftTags: ['nature'],
  },
  {
    id: 'moon_keyring',
    name: '달 키링',
    description: '달 모양 키링. 밤에 보면 아주 옅게 빛난다.',
    type: 'EQUIPMENT',
    rarity: 'EPIC',
    icon: '🌙',
    equipSlot: 'ACCESSORY',
    effectLabel: '마음 EXP +7%',
    bonuses: { expPctByCategory: { MIND: 7 } },
    giftTags: ['moon', 'collectible'],
  },
  {
    id: 'star_pin',
    name: '별 핀',
    description: 'Noa 가 준 별 모양 핀. 어디서 났는지는 안 알려줬다.',
    type: 'EQUIPMENT',
    rarity: 'EPIC',
    icon: '🌟',
    equipSlot: 'HEAD',
    effectLabel: '관계 보상 +10%',
    bonuses: { rewardPctByCategory: { HEART: 10 } },
    giftTags: ['moon', 'collectible'],
  },
  {
    id: 'night_ticket',
    name: '밤 시장 표',
    description: '밤 시장에서만 받는 표. 뭘 살 수 있는지는 그날 봐야 안다.',
    type: 'COLLECTIBLE',
    rarity: 'RARE',
    icon: '🎫',
    equipSlot: null,
    effectLabel: '아직 쓸 곳이 없다',
    bonuses: {},
    giftTags: ['moon', 'collectible'],
  },
  {
    id: 'lucky_cat_sticker',
    name: '행운 고양이 스티커',
    description: '공원 벤치에 붙어 있던 스티커. 왠지 떼기 아까웠다.',
    type: 'COLLECTIBLE',
    rarity: 'COMMON',
    icon: '🐱',
    equipSlot: null,
    effectLabel: '아직 쓸 곳이 없다',
    bonuses: {},
    giftTags: ['collectible', 'nature'],
  },
  {
    id: 'flower_bookmark',
    name: '꽃 책갈피',
    description: '말린 꽃을 끼워 만든 책갈피.',
    type: 'COLLECTIBLE',
    rarity: 'COMMON',
    icon: '🔖',
    equipSlot: null,
    effectLabel: '아직 쓸 곳이 없다',
    bonuses: {},
    giftTags: ['book', 'nature', 'art'],
  },
]

export function findItem(id: string): ItemDef | null {
  return ITEMS.find((i) => i.id === id) ?? null
}

// ── 몬스터 ──────────────────────────────────────────────
//
// 몬스터는 **미루기 쉬운 작은 일** 이다. 행동 3~4개면 끝난다.
// 이름은 중세 판타지가 아니라 생활에서 가져온다 — 싱크대에 사는 것,
// 의자 위에 쌓인 것, 답장 안 한 것. 그래야 잡는 게 현실에서도 뭔가 끝난다.
//
// 각 행동의 match 는 그 행동과 같은 일을 가리키는 퀘스트 제목 조각이다.
// 퀘스트를 완료하면 여기가 자동으로 채워진다 (lib/rpg/link.ts).
export const MONSTERS: BattleDef[] = [
  // ── 집안일 ────────────────────────────────────────────
  {
    id: 'dish_slime',
    kind: 'MONSTER',
    name: '설거지 슬라임',
    description: '싱크대에서 조금씩 자라는 녀석.',
    category: 'LIFE',
    icon: '🍽️',
    maxHp: 40,
    actions: [
      { label: '컵 씻기', damage: 10, match: ['컵씻', '컵정리'] },
      { label: '접시 정리', damage: 15, match: ['그릇', '접시'] },
      { label: '프라이팬 씻기', damage: 15, match: ['설거지'] },
    ],
    rewardExp: 40,
    rewardCoins: 60,
    guaranteedRarity: 'COMMON',
  },
  {
    id: 'laundry_blob',
    kind: 'MONSTER',
    name: '빨래 덩어리',
    description: '빨래 바구니에서 부풀어 오른 덩어리.',
    category: 'LIFE',
    icon: '🧺',
    maxHp: 60,
    actions: [
      { label: '세탁기 돌리기', damage: 20, match: ['빨래돌리', '세탁'] },
      { label: '널기', damage: 20, match: ['널기', '건조', '말리'] },
      { label: '개서 넣기', damage: 20, match: ['빨래개', '개서넣'] },
    ],
    rewardExp: 60,
    rewardCoins: 90,
    guaranteedRarity: 'COMMON',
  },
  {
    id: 'dust_bunny',
    kind: 'MONSTER',
    name: '먼지뭉치',
    description: '가구 밑에서 조용히 몸집을 불린다.',
    category: 'LIFE',
    icon: '🌫️',
    maxHp: 60,
    actions: [
      { label: '바닥 물건 치우기', damage: 20, match: ['바닥물건', '물건하나'] },
      { label: '바닥 쓸기', damage: 20, match: ['바닥청소', '바닥닦', '청소'] },
      { label: '환기하기', damage: 20, match: ['환기'] },
    ],
    rewardExp: 60,
    rewardCoins: 90,
    guaranteedRarity: 'COMMON',
  },
  {
    id: 'chair_pile',
    kind: 'MONSTER',
    name: '옷의자 괴물',
    description: '의자인지 옷더미인지 이제 아무도 모른다.',
    category: 'LIFE',
    icon: '🪑',
    maxHp: 60,
    actions: [
      { label: '입을 것과 빨 것 나누기', damage: 20, match: ['의자위', '의자에쌓인'] },
      { label: '옷장에 넣기', damage: 20, match: ['옷장'] },
      { label: '의자 닦기', damage: 20, match: ['의자닦'] },
    ],
    rewardExp: 60,
    rewardCoins: 90,
    guaranteedRarity: 'COMMON',
  },
  {
    id: 'box_legion',
    kind: 'MONSTER',
    name: '택배상자 군단',
    description: '하나 버리면 다음 주에 둘이 온다.',
    category: 'LIFE',
    icon: '🚚',
    maxHp: 50,
    actions: [
      { label: '상자 접기', damage: 20, match: ['택배상자', '상자'] },
      { label: '포장재 빼내기', damage: 15, match: ['포장재', '뽁뽁이'] },
      { label: '분리배출 하러 나가기', damage: 15, match: ['분리배출', '재활용'] },
    ],
    rewardExp: 50,
    rewardCoins: 75,
    guaranteedRarity: 'COMMON',
  },
  {
    id: 'fridge_ghost',
    kind: 'MONSTER',
    name: '냉장고 유령',
    description: '언제 넣었는지 아무도 기억 못 하는 것이 안쪽에 있다.',
    category: 'LIFE',
    icon: '🧊',
    maxHp: 80,
    actions: [
      { label: '한 칸씩 꺼내보기', damage: 25, match: ['냉장고한칸', '냉장고확인'] },
      { label: '오래된 것 버리기', damage: 30, match: ['오래된음식', '유통기한'] },
      { label: '선반 한 번 닦기', damage: 25, match: ['냉장고정리'] },
    ],
    rewardExp: 80,
    rewardCoins: 120,
    guaranteedRarity: 'RARE',
  },
  {
    id: 'clutter_mimic',
    kind: 'MONSTER',
    name: '잡동사니 미믹',
    description: '열어보기 전까진 뭐가 들었는지 모르는 서랍.',
    category: 'LIFE',
    icon: '📦',
    maxHp: 100,
    actions: [
      { label: '전부 꺼내기', damage: 30, match: ['서랍'] },
      { label: '버릴 것 버리기', damage: 40, match: ['안쓰는물건', '다섯개버리'] },
      { label: '자리 정해 넣기', damage: 30, match: ['제자리'] },
    ],
    rewardExp: 100,
    rewardCoins: 150,
    guaranteedRarity: 'RARE',
    bonusRarity: 'EPIC',
  },

  // ── 일 · 공부 ─────────────────────────────────────────
  {
    id: 'mail_goblin',
    kind: 'MONSTER',
    name: '메일 고블린',
    description: '읽씹한 메일함에 사는 고블린.',
    category: 'WORK',
    icon: '✉️',
    maxHp: 50,
    actions: [
      { label: '급한 것부터 답장', damage: 25, match: ['이메일답장', '메일답장'] },
      { label: '나머지 훑기', damage: 15, match: ['메일또는', '메신저'] },
      { label: '정리·보관', damage: 10, match: ['메일함'] },
    ],
    rewardExp: 50,
    rewardCoins: 75,
    guaranteedRarity: 'COMMON',
  },
  {
    id: 'reply_ghost',
    kind: 'MONSTER',
    name: '답장 유령',
    description: '읽고 나서 나중에 하려던 그 메시지.',
    category: 'HEART',
    icon: '💬',
    maxHp: 45,
    actions: [
      { label: '제일 오래된 것 하나', damage: 20, match: ['미뤄둔답장', '밀린답장'] },
      { label: '짧게라도 답하기', damage: 15, match: ['답장하나', '답장'] },
      { label: '안부 한 줄 남기기', damage: 10, match: ['안부'] },
    ],
    rewardExp: 45,
    rewardCoins: 70,
    guaranteedRarity: 'COMMON',
  },
  {
    id: 'deadline_shade',
    kind: 'MONSTER',
    name: '마감 그림자',
    description: '아직 멀었다고 생각하는 동안 조용히 가까워진다.',
    category: 'WORK',
    icon: '⏰',
    maxHp: 90,
    actions: [
      { label: '뭘 내야 하는지 확인', damage: 25, match: ['마감확인', '뭘내야'] },
      { label: '한 조각 해두기', damage: 35, match: ['첫조각', '업무진행'] },
      { label: '제출하기', damage: 30, match: ['제출', '보내버리'] },
    ],
    rewardExp: 90,
    rewardCoins: 135,
    guaranteedRarity: 'RARE',
  },
  {
    id: 'tab_swarm',
    kind: 'MONSTER',
    name: '탭 증식체',
    description: '나중에 볼 거라며 열어둔 것들이 서로를 부른다.',
    category: 'WORK',
    icon: '🗂️',
    maxHp: 45,
    actions: [
      { label: '다시 안 볼 것 닫기', damage: 20, match: ['탭정리', '브라우저'] },
      { label: '볼 것만 저장해두기', damage: 15, match: ['자료정리'] },
      { label: '창 하나로 줄이기', damage: 10, match: ['파일·탭', '불필요한파일'] },
    ],
    rewardExp: 45,
    rewardCoins: 70,
    guaranteedRarity: 'COMMON',
  },
  {
    id: 'unread_docs',
    kind: 'MONSTER',
    name: '읽지 않은 문서',
    description: '열어는 봤지만 첫 문단에서 멈춘 것들.',
    category: 'WORK',
    icon: '📄',
    maxHp: 80,
    actions: [
      { label: '제목만 훑어보기', damage: 20, match: ['자료찾', '문서확인'] },
      { label: '필요한 데만 읽기', damage: 30, match: ['자료읽', '자료하나읽', '복습'] },
      { label: '요약 한 줄 남기기', damage: 30, match: ['자료하나정리'] },
    ],
    rewardExp: 80,
    rewardCoins: 120,
    guaranteedRarity: 'RARE',
  },
  {
    id: 'stale_files',
    kind: 'MONSTER',
    name: '미뤄둔 파일',
    description: '최종_최종_진짜최종 사이 어딘가에 있다.',
    category: 'WORK',
    icon: '🗄️',
    maxHp: 100,
    actions: [
      { label: '어디까지 했는지 열어보기', damage: 30, match: ['파일하나', '파일정리'] },
      { label: '한 덩어리만 손보기', damage: 35, match: ['문서하나'] },
      { label: '이름 붙여 저장하기', damage: 35, match: ['폴더정리', '백업'] },
    ],
    rewardExp: 100,
    rewardCoins: 150,
    guaranteedRarity: 'RARE',
  },
  {
    id: 'task_hydra',
    kind: 'MONSTER',
    name: '할 일 히드라',
    description: '하나 끝내면 두 개가 생기는 그 일.',
    category: 'WORK',
    icon: '🐉',
    maxHp: 120,
    actions: [
      { label: '할 일 쪼개 적기', damage: 20, match: ['쪼개', '머릿속할일'] },
      { label: '제일 작은 것 하나', damage: 25, match: ['작은일하나'] },
      { label: '중간 것 하나', damage: 35, match: ['25분집중', '20분'] },
      { label: '남은 것 마무리', damage: 40, match: ['마무리', '끝까지'] },
    ],
    rewardExp: 120,
    rewardCoins: 180,
    guaranteedRarity: 'RARE',
  },

  // ── 생활관리 ──────────────────────────────────────────
  {
    id: 'receipt_heap',
    kind: 'MONSTER',
    name: '영수증 더미',
    description: '지갑에서도 가방에서도 계속 나온다.',
    category: 'LIFE',
    icon: '🧾',
    maxHp: 60,
    actions: [
      { label: '한군데 모으기', damage: 20, match: ['영수증'] },
      { label: '이번 달 지출 보기', damage: 20, match: ['지출', '예산'] },
      { label: '버릴 것 버리기', damage: 20, match: ['결제확인', '예정결제'] },
    ],
    rewardExp: 60,
    rewardCoins: 90,
    guaranteedRarity: 'COMMON',
  },
  {
    id: 'booking_dodger',
    kind: 'MONSTER',
    name: '예약 미루미',
    description: '전화만 걸면 되는데 그 전화가 제일 어렵다.',
    category: 'LIFE',
    icon: '📅',
    maxHp: 80,
    actions: [
      { label: '언제가 되는지 보기', damage: 20, match: ['일정확인', '날짜정하'] },
      { label: '어디로 할지 정하기', damage: 25, match: ['미뤄둔예약'] },
      { label: '예약 넣기', damage: 35, match: ['병원', '검진'] },
    ],
    rewardExp: 80,
    rewardCoins: 120,
    guaranteedRarity: 'RARE',
  },
  {
    id: 'form_eater',
    kind: 'MONSTER',
    name: '서류 먹보',
    description: '한 장을 내면 두 장을 더 달라고 한다.',
    category: 'LIFE',
    icon: '📋',
    maxHp: 90,
    actions: [
      { label: '뭐가 필요한지 확인', damage: 25, match: ['보험', '서류확인'] },
      { label: '빈칸 채우기', damage: 30, match: ['신청', '접수'] },
      { label: '내기', damage: 35, match: ['미뤄둔서류', '서류처리'] },
    ],
    rewardExp: 90,
    rewardCoins: 135,
    guaranteedRarity: 'RARE',
  },
  {
    id: 'notif_clump',
    kind: 'MONSTER',
    name: '알림 덩어리',
    description: '빨간 점들이 서로 뭉쳐 하나가 됐다.',
    category: 'LIFE',
    icon: '🔔',
    maxHp: 40,
    actions: [
      { label: '뭐가 와 있는지 보기', damage: 15, match: ['알림하나'] },
      { label: '해치울 것 하나 해치우기', damage: 15, match: ['미뤄둔작은일'] },
      { label: '안 볼 알림 끄기', damage: 10, match: ['알림·구독', '구독서비스'] },
    ],
    rewardExp: 40,
    rewardCoins: 60,
    guaranteedRarity: 'COMMON',
  },
  {
    id: 'photo_cloud',
    kind: 'MONSTER',
    name: '사진구름',
    description: '저장공간 부족 알림이 뜨는 진짜 이유.',
    category: 'LIFE',
    icon: '🖼️',
    maxHp: 100,
    actions: [
      { label: '스크린샷부터 지우기', damage: 30, match: ['스크린샷'] },
      { label: '흔들린 것 골라내기', damage: 35, match: ['사진정리', '사진대량'] },
      { label: '남길 것 백업하기', damage: 35, match: ['다운로드폴더'] },
    ],
    rewardExp: 100,
    rewardCoins: 150,
    guaranteedRarity: 'RARE',
    bonusRarity: 'EPIC',
  },

  // ── 몸 · 마음 ─────────────────────────────────────────
  {
    id: 'stiff_shoulder',
    kind: 'MONSTER',
    name: '굳은 어깨',
    description: '언제부터 이랬는지 기억나지 않는다.',
    category: 'BODY',
    icon: '🪨',
    maxHp: 50,
    actions: [
      { label: '한 번 일어나기', damage: 15, match: ['일어나기', '오래앉'] },
      { label: '목과 어깨 풀기', damage: 20, match: ['목과어깨', '목어깨'] },
      { label: '길게 늘여주기', damage: 15, match: ['스트레칭'] },
    ],
    rewardExp: 50,
    rewardCoins: 75,
    guaranteedRarity: 'COMMON',
  },
  {
    id: 'couch_moss',
    kind: 'MONSTER',
    name: '소파 이끼',
    description: '앉아 있으면 조금씩 자란다. 아프지는 않다.',
    category: 'BODY',
    icon: '🛋️',
    maxHp: 70,
    actions: [
      { label: '신발 신기', damage: 20, match: ['신발신고', '문밖'] },
      { label: '문밖까지 나가기', damage: 25, match: ['산책', '바깥공기'] },
      { label: '한 바퀴 걷고 오기', damage: 25, match: ['걷기', '한정거장'] },
    ],
    rewardExp: 70,
    rewardCoins: 105,
    guaranteedRarity: 'COMMON',
  },
  {
    id: 'blank_page',
    kind: 'MONSTER',
    name: '빈 페이지',
    description: '쓸 게 없는 게 아니라 첫 줄이 무거운 것이다.',
    category: 'MIND',
    icon: '📃',
    maxHp: 50,
    actions: [
      { label: '한 문장만 적기', damage: 15, match: ['한문장', '한줄'] },
      { label: '오늘 있었던 일 적기', damage: 20, match: ['일기'] },
      { label: '좋았던 것 하나 적기', damage: 15, match: ['감사한일', '잘한일'] },
    ],
    rewardExp: 50,
    rewardCoins: 75,
    guaranteedRarity: 'COMMON',
  },
  {
    id: 'night_scroll',
    kind: 'MONSTER',
    name: '밤의 스크롤',
    description: '내릴수록 아래가 더 생긴다. 끝은 원래 없다.',
    category: 'MIND',
    icon: '📱',
    maxHp: 60,
    actions: [
      { label: '화면 내려놓기', damage: 20, match: ['화면잠시', '업무화면'] },
      { label: '폰 손 안 닿는 곳에 두기', damage: 20, match: ['폰손안닿', '폰다른방', '폰안보'] },
      { label: '불 끄고 눕기', damage: 20, match: ['정한시간에눕', '잠자리', '조명낮'] },
    ],
    rewardExp: 60,
    rewardCoins: 90,
    guaranteedRarity: 'COMMON',
  },
]

// ── 보스 ────────────────────────────────────────────────
//
// 보스는 **센 몬스터가 아니다.** 여러 현실 행동이 이어져야 끝나는,
// 조금 큰 현실 프로젝트다. 그래서 대부분 행동이 3~5개다.
// 체크리스트가 길어지면 그건 보스가 아니라 또 하나의 부담이다.
export const BOSSES: BattleDef[] = [
  {
    id: 'deadline_dragon',
    kind: 'BOSS',
    name: '마감 드래곤',
    description: '달력에 빨갛게 표시해둔 그날의 주인.',
    category: 'WORK',
    icon: '🔥',
    maxHp: 300,
    actions: [
      { label: '자료 조사', damage: 50, match: ['자료찾', '리서치'] },
      { label: '초안 작성', damage: 80, match: ['첫조각', '초안'] },
      { label: '수정', damage: 70, match: ['한시간붙어', '보고서'] },
      { label: '최종 검수', damage: 100, match: ['끝까지마무리', '문서하나끝'] },
    ],
    rewardExp: 300,
    rewardCoins: 360,
    guaranteedRarity: 'RARE',
    bonusRarity: 'EPIC',
  },
  {
    id: 'cleaning_golem',
    kind: 'BOSS',
    name: '대청소 골렘',
    description: '집 전체가 한 덩어리로 뭉친 것.',
    category: 'LIFE',
    icon: '🧹',
    maxHp: 250,
    actions: [
      { label: '바닥 치우기', damage: 60, match: ['바닥청소', '바닥물건'] },
      { label: '먼지 닦기', damage: 60, match: ['가볍게청소', '책상·화장대'] },
      { label: '욕실', damage: 60, match: ['욕실'] },
      { label: '마지막 정리', damage: 70, match: ['방한구역'] },
    ],
    rewardExp: 250,
    rewardCoins: 300,
    guaranteedRarity: 'RARE',
    bonusRarity: 'EPIC',
  },
  {
    id: 'monday_shadow',
    kind: 'BOSS',
    name: '월요일 그림자',
    description: '일요일 밤부터 따라오는 그림자.',
    category: 'MIND',
    icon: '🌑',
    maxHp: 180,
    actions: [
      { label: '이번 주 할 일 적기', damage: 60, match: ['다음주필요', '머릿속할일'] },
      { label: '우선순위 정하기', damage: 60, match: ['중요한일하나', '세가지정해'] },
      { label: '첫 한 개 시작', damage: 60, match: ['제일미룬일시작'] },
    ],
    rewardExp: 180,
    rewardCoins: 240,
    guaranteedRarity: 'COMMON',
    bonusRarity: 'RARE',
  },
  {
    id: 'laundry_overlord',
    kind: 'BOSS',
    name: '빨래 대마왕',
    description: '바구니 하나로는 이제 감당이 안 된다.',
    category: 'LIFE',
    icon: '👕',
    maxHp: 200,
    actions: [
      { label: '한 통 돌리기', damage: 50, match: ['빨래돌리', '세탁'] },
      { label: '널어 말리기', damage: 50, match: ['널기', '건조'] },
      { label: '개기', damage: 50, match: ['빨래개', '개서넣'] },
      { label: '옷장에 넣기', damage: 50, match: ['옷장'] },
    ],
    rewardExp: 200,
    rewardCoins: 250,
    guaranteedRarity: 'RARE',
  },
  {
    id: 'room_chaos',
    kind: 'BOSS',
    name: '방구석 혼돈체',
    description: '어디부터 손대야 할지 모르겠는 그 상태.',
    category: 'LIFE',
    icon: '🌀',
    maxHp: 250,
    actions: [
      { label: '쓰레기부터 버리기', damage: 45, match: ['쓰레기'] },
      { label: '바닥 비우기', damage: 50, match: ['바닥물건', '바닥청소'] },
      { label: '의자 위 치우기', damage: 50, match: ['의자위', '의자에쌓인'] },
      { label: '책상 정리', damage: 50, match: ['책상'] },
      { label: '잡동사니 자리 정하기', damage: 55, match: ['서랍', '제자리'] },
    ],
    rewardExp: 250,
    rewardCoins: 300,
    guaranteedRarity: 'RARE',
    bonusRarity: 'EPIC',
  },
  {
    id: 'fridge_abyss',
    kind: 'BOSS',
    name: '냉장고 심연',
    description: '안쪽 깊은 곳은 아직 아무도 본 적이 없다.',
    category: 'LIFE',
    icon: '🥶',
    maxHp: 200,
    actions: [
      { label: '전부 꺼내보기', damage: 50, match: ['냉장고한칸', '냉장고확인'] },
      { label: '오래된 것 버리기', damage: 50, match: ['오래된음식', '유통기한'] },
      { label: '선반 닦기', damage: 50, match: ['냉장고정리'] },
      { label: '필요한 것 적어두기', damage: 50, match: ['장보기목록', '구매목록'] },
    ],
    rewardExp: 200,
    rewardCoins: 250,
    guaranteedRarity: 'RARE',
  },
  {
    id: 'paper_mountain',
    kind: 'BOSS',
    name: '서류의 산',
    description: '언젠가 해야지 하고 쌓아둔 것이 산이 됐다.',
    category: 'LIFE',
    icon: '🗒️',
    maxHp: 220,
    actions: [
      { label: '뭐가 있는지 확인', damage: 50, match: ['보험', '서류확인'] },
      { label: '필요한 것 챙기기', damage: 55, match: ['갱신', '연장'] },
      { label: '작성하기', damage: 55, match: ['신청', '접수'] },
      { label: '제출하기', damage: 60, match: ['미뤄둔서류', '서류처리'] },
    ],
    rewardExp: 220,
    rewardCoins: 270,
    guaranteedRarity: 'RARE',
    bonusRarity: 'EPIC',
  },
  {
    id: 'deadline_storm',
    kind: 'BOSS',
    name: '마감 폭풍',
    description: '여러 개가 같은 주에 몰려 있을 때의 이름.',
    category: 'WORK',
    icon: '🌪️',
    maxHp: 280,
    actions: [
      { label: '일 열기', damage: 50, match: ['필요한파일만', '업무시작'] },
      { label: '자료 정리', damage: 55, match: ['자료하나정리', '파일·폴더'] },
      { label: '작업하기', damage: 60, match: ['50분', '한시간붙어'] },
      { label: '검토', damage: 55, match: ['끝까지마무리'] },
      { label: '내보내기', damage: 60, match: ['제출', '보내버리'] },
    ],
    rewardExp: 280,
    rewardCoins: 340,
    guaranteedRarity: 'RARE',
    bonusRarity: 'EPIC',
  },
  {
    id: 'backlog_lump',
    kind: 'BOSS',
    name: '밀린 일의 덩어리',
    description: '따로 보면 별거 아닌데 뭉쳐 있어서 안 건드려진다.',
    category: 'WORK',
    icon: '🧱',
    maxHp: 210,
    actions: [
      { label: '전부 적어서 펼쳐놓기', damage: 45, match: ['머릿속할일', '쪼개'] },
      { label: '제일 작은 것 하나', damage: 50, match: ['미뤄둔작은일'] },
      { label: '제일 무거운 것 시작', damage: 55, match: ['제일미룬일시작', '제일미루고'] },
      { label: '하나 끝내버리기', damage: 60, match: ['문서하나끝', '중요한메일'] },
    ],
    rewardExp: 210,
    rewardCoins: 260,
    guaranteedRarity: 'RARE',
  },
  {
    id: 'digital_junk',
    kind: 'BOSS',
    name: '디지털 잡동사니',
    description: '눈에 안 보여서 더 오래 남아 있는 것들.',
    category: 'LIFE',
    icon: '💾',
    maxHp: 200,
    actions: [
      { label: '다운로드 폴더', damage: 50, match: ['다운로드폴더'] },
      { label: '사진과 스크린샷', damage: 50, match: ['사진정리', '스크린샷', '사진대량'] },
      { label: '메일함', damage: 50, match: ['메일함'] },
      { label: '파일 자리 잡아주기', damage: 50, match: ['파일·폴더', '파일하나'] },
    ],
    rewardExp: 200,
    rewardCoins: 250,
    guaranteedRarity: 'RARE',
  },
  {
    id: 'call_delayer',
    kind: 'BOSS',
    name: '연락 미루미',
    description: '늦었다고 생각할수록 더 못 하게 되는 그것.',
    category: 'HEART',
    icon: '📞',
    maxHp: 180,
    actions: [
      { label: '답장 하나', damage: 45, match: ['미뤄둔답장', '밀린답장', '답장하나'] },
      { label: '가족에게 먼저', damage: 45, match: ['가족에게먼저', '부모님'] },
      { label: '오래 못 본 사람에게', damage: 45, match: ['오래연락못한', '오래못본'] },
      { label: '해야 하는 전화 한 통', damage: 45, match: ['전화한통'] },
    ],
    rewardExp: 180,
    rewardCoins: 220,
    guaranteedRarity: 'COMMON',
    bonusRarity: 'RARE',
  },
  {
    id: 'week_leftover',
    kind: 'BOSS',
    name: '한 주의 잔여물',
    description: '이번 주에 안 한 것들이 조용히 다음 주로 넘어가 있다.',
    category: 'MIND',
    icon: '🗓️',
    maxHp: 190,
    actions: [
      { label: '한 주 돌아보기', damage: 45, match: ['한주돌아보'] },
      { label: '집에 남은 것 하나', damage: 45, match: ['가볍게청소', '침구'] },
      { label: '생활에 남은 것 하나', damage: 45, match: ['예산', '지출'] },
      { label: '다음 주 준비', damage: 55, match: ['다음주필요'] },
    ],
    rewardExp: 190,
    rewardCoins: 230,
    guaranteedRarity: 'RARE',
  },
  {
    id: 'body_rust',
    kind: 'BOSS',
    name: '굳어버린 몸',
    description: '하루 이틀이 아니라서, 하루 이틀로는 안 풀린다.',
    category: 'BODY',
    icon: '🏋️',
    maxHp: 190,
    actions: [
      { label: '준비만 해두기', damage: 40, match: ['운동할준비'] },
      { label: '길게 늘여주기', damage: 45, match: ['전신스트레칭', '10분스트레칭'] },
      { label: '걷기', damage: 50, match: ['30분걷기', '계단'] },
      { label: '제대로 한 번', damage: 55, match: ['30분운동'] },
    ],
    rewardExp: 190,
    rewardCoins: 230,
    guaranteedRarity: 'RARE',
  },
]

export const BATTLE_DEFS = [...MONSTERS, ...BOSSES]

export function findBattleDef(id: string): BattleDef | null {
  return BATTLE_DEFS.find((b) => b.id === id) ?? null
}
