import type { AreaDef, BattleDef, ClassDef, ItemDef } from '@/types'

/**
 * 이번 업데이트의 모든 밸런스 값이 여기 모여 있다.
 * 숫자를 고칠 일이 생기면 이 파일만 열면 된다.
 *
 * 검·갑옷·성 대신 머그컵·헤드폰·운동화·카페·공원으로 만든다.
 */

// ── 지역 ────────────────────────────────────────────────
export const AREAS: AreaDef[] = [
  {
    id: 'HOME_BASE',
    name: '우리 집',
    icon: '🏠',
    description: '쉬고, 정리하고, 하루를 다시 시작하는 나의 작은 자리.',
    categories: ['LIFE', 'MIND'],
    buffName: '집의 편안함',
    buffLabel: '생활 · 마음 EXP +5%',
    bonuses: { expPctByCategory: { LIFE: 5, MIND: 5 } },
  },
  {
    id: 'CAFE_STREET',
    name: '카페 거리',
    icon: '☕',
    description: '커피 한 잔 놓고 집중이 잘 붙는 거리.',
    categories: ['WORK', 'MIND'],
    buffName: '깊은 집중',
    buffLabel: '일 EXP +10%',
    bonuses: { expPctByCategory: { WORK: 10 } },
  },
  {
    id: 'GREEN_PARK',
    name: '초록 공원',
    icon: '🌳',
    description: '바람이 통하는 곳. 몸을 움직이거나 사람을 만나기 좋다.',
    categories: ['BODY', 'HEART'],
    buffName: '맑은 공기',
    buffLabel: '몸 EXP +10%',
    bonuses: { expPctByCategory: { BODY: 10 } },
  },
  {
    id: 'CREATIVE_DISTRICT',
    name: '창작 골목',
    icon: '🎨',
    description: '뭔가 만들고 싶어지는 동네. 좋은 게 자주 굴러다닌다.',
    categories: ['PLAY', 'MIND'],
    buffName: '영감',
    buffLabel: '놀이 EXP +10% · 귀함 드롭 +3%',
    bonuses: { expPctByCategory: { PLAY: 10 }, rareDropChancePct: 3 },
  },
  {
    id: 'TRAINING_ZONE',
    name: '운동 구역',
    icon: '👟',
    description: '몸 쓰는 일에만 집중하는 공간.',
    categories: ['BODY'],
    buffName: '훈련 모드',
    buffLabel: '몸 보상 +15%',
    bonuses: { rewardPctByCategory: { BODY: 15 } },
  },
  {
    id: 'NIGHT_TOWN',
    name: '밤의 거리',
    icon: '🌙',
    description: '조용해진 도시. 생각을 정리하기 좋은 시간.',
    categories: ['MIND', 'LIFE', 'HEART'],
    buffName: '밤의 고요',
    buffLabel: '마음 EXP +10%',
    bonuses: { expPctByCategory: { MIND: 10 } },
    nightOnly: true,
  },
]

export function findArea(id: string): AreaDef {
  return AREAS.find((a) => a.id === id) ?? AREAS[0]
}

// ── 직업 ────────────────────────────────────────────────
export const CLASSES: ClassDef[] = [
  {
    id: 'PLANNER',
    name: '계획하는 사람',
    icon: '🗓️',
    description: '큰 일을 쪼개서 끝까지 가는 사람.',
    passiveName: '꾸준한 계획',
    passiveLabel: '어려움 퀘스트 EXP +5%',
    bonuses: { hardExpPct: 5 },
  },
  {
    id: 'MAKER',
    name: '만드는 사람',
    icon: '🛠️',
    description: '만들면서 배우는 사람. 좋은 걸 잘 주워온다.',
    passiveName: '좋은 눈',
    passiveLabel: '귀함 이상 드롭 +3%',
    bonuses: { rareDropChancePct: 3 },
  },
  {
    id: 'EXPLORER',
    name: '돌아다니는 사람',
    icon: '🧭',
    description: '어디든 한번 가보는 사람. 주머니가 잘 찬다.',
    passiveName: '기념품',
    // 명세의 "Random Quest reward +10%" 를 지금 구조에 맞게 옮겼다 (README 에 적어둠)
    passiveLabel: '모든 퀘스트 코인 +10%',
    bonuses: { coinPct: 10 },
  },
  {
    id: 'CARETAKER',
    name: '돌보는 사람',
    icon: '🧺',
    description: '나와 주변을 돌보는 사람.',
    passiveName: '따뜻한 손',
    passiveLabel: '생활 · 마음 EXP +3%',
    bonuses: { expPctByCategory: { LIFE: 3, MIND: 3 } },
  },
  {
    id: 'MOVER',
    name: '움직이는 사람',
    icon: '🏃',
    description: '일단 몸을 움직이고 보는 사람.',
    passiveName: '몸이 풀림',
    passiveLabel: '몸 EXP +10%',
    bonuses: { expPctByCategory: { BODY: 10 } },
  },
]

export function findClass(id: string | null): ClassDef | null {
  return CLASSES.find((c) => c.id === id) ?? null
}

// ── 아이템 ──────────────────────────────────────────────
export const ITEMS: ItemDef[] = [
  // COMMON
  {
    id: 'favorite_mug',
    name: '애착 머그컵',
    description: '손에 익은 머그컵. 이걸로 마셔야 생각이 정리된다.',
    type: 'EQUIPMENT',
    rarity: 'COMMON',
    icon: '☕',
    equipSlot: 'CHARM',
    effectLabel: '마음 EXP +3%',
    bonuses: { expPctByCategory: { MIND: 3 } },
    giftTags: ['coffee', 'cozy'],
  },
  {
    id: 'tiny_hair_clip',
    name: '작은 머리핀',
    description: '앞머리를 넘길 때 쓰는 작은 핀. 왠지 운이 좋다.',
    type: 'EQUIPMENT',
    rarity: 'COMMON',
    icon: '🎀',
    equipSlot: 'ACCESSORY',
    effectLabel: '행운 +1',
    bonuses: { luck: 1 },
    giftTags: ['collectible'],
  },
  {
    id: 'cozy_hoodie',
    name: '포근한 후드',
    description: '집에서 제일 많이 입는 후드. 입으면 일단 편하다.',
    type: 'EQUIPMENT',
    rarity: 'COMMON',
    icon: '🧥',
    equipSlot: 'TOP',
    effectLabel: '생활 EXP +3%',
    bonuses: { expPctByCategory: { LIFE: 3 } },
  },
  {
    id: 'daily_sneakers',
    name: '매일 신는 운동화',
    description: '아무 데나 신고 나가는 운동화.',
    type: 'EQUIPMENT',
    rarity: 'COMMON',
    icon: '👟',
    equipSlot: 'SHOES',
    effectLabel: '몸 EXP +3%',
    bonuses: { expPctByCategory: { BODY: 3 } },
  },
  {
    id: 'soft_cap',
    name: '푹신한 모자',
    description: '머리 안 감은 날의 친구.',
    type: 'EQUIPMENT',
    rarity: 'COMMON',
    icon: '🧢',
    equipSlot: 'HEAD',
    effectLabel: '놀이 EXP +2%',
    bonuses: { expPctByCategory: { PLAY: 2 } },
  },
  {
    id: 'comfort_shorts',
    name: '편한 반바지',
    description: '집안일 할 때 제일 편한 반바지.',
    type: 'EQUIPMENT',
    rarity: 'COMMON',
    icon: '🩳',
    equipSlot: 'BOTTOM',
    effectLabel: '생활 EXP +2%',
    bonuses: { expPctByCategory: { LIFE: 2 } },
  },

  // RARE
  {
    id: 'noise_cancelling_headphones',
    name: '노이즈 캔슬링 헤드폰',
    description: '쓰는 순간 세상이 조용해진다.',
    type: 'EQUIPMENT',
    rarity: 'RARE',
    icon: '🎧',
    equipSlot: 'ACCESSORY',
    effectLabel: '일 EXP +5%',
    bonuses: { expPctByCategory: { WORK: 5 } },
  },
  {
    id: 'lucky_sneakers',
    name: '행운의 운동화',
    description: '이걸 신은 날은 이상하게 더 걷게 된다.',
    type: 'EQUIPMENT',
    rarity: 'RARE',
    icon: '✨',
    equipSlot: 'SHOES',
    effectLabel: '몸 EXP +5%',
    bonuses: { expPctByCategory: { BODY: 5 } },
  },
  {
    id: 'adventure_tote',
    name: '모험 가방',
    description: '뭐든 일단 담아오는 가방.',
    type: 'EQUIPMENT',
    rarity: 'RARE',
    icon: '👜',
    equipSlot: 'ACCESSORY',
    effectLabel: '드롭 확률 +2%',
    bonuses: { dropChancePct: 2 },
  },
  {
    id: 'focus_watch',
    name: '집중 시계',
    description: '남은 시간을 보면 이상하게 더 집중된다.',
    type: 'EQUIPMENT',
    rarity: 'RARE',
    icon: '⌚',
    equipSlot: 'ACCESSORY',
    effectLabel: '어려움 퀘스트 EXP +5%',
    bonuses: { hardExpPct: 5 },
  },

  // EPIC
  {
    id: 'lucky_keyring',
    name: '행운의 키링',
    description: '언제 생겼는지 모를 키링. 좋은 일이 자주 따라온다.',
    type: 'EQUIPMENT',
    rarity: 'EPIC',
    icon: '🔑',
    equipSlot: 'CHARM',
    effectLabel: '귀함 이상 드롭 +4%',
    bonuses: { rareDropChancePct: 4 },
  },
  {
    id: 'perfect_work_headset',
    name: '완벽한 작업 헤드셋',
    description: '쓰면 오늘 할 일이 갑자기 할 만해 보인다.',
    type: 'EQUIPMENT',
    rarity: 'EPIC',
    icon: '🎙️',
    equipSlot: 'HEAD',
    effectLabel: '일 EXP +8%',
    bonuses: { expPctByCategory: { WORK: 8 } },
  },

  // LEGENDARY — 구조만 열어두고 실제 드롭은 이번 버전에 없다
  {
    id: 'star_fragment',
    name: '별 조각',
    description: '어느 밤 주머니에 들어와 있던 별 조각.',
    type: 'COLLECTIBLE',
    rarity: 'LEGENDARY',
    icon: '⭐',
    equipSlot: null,
    effectLabel: '아직 쓸 곳이 없다',
    bonuses: {},
    giftTags: ['moon', 'collectible'],
  },

  // MATERIAL — placeholder
  {
    id: 'spare_button',
    name: '여분 단추',
    description: '언젠가 쓸 것 같아서 모아둔 단추.',
    type: 'MATERIAL',
    rarity: 'COMMON',
    icon: '🔘',
    equipSlot: null,
    effectLabel: '아직 쓸 곳이 없다',
    bonuses: {},
    giftTags: ['collectible'],
  },

  // ── 도시에서 얻는 것들 ────────────────────────────────
  // 마시는 것 — 다음 퀘스트 한 번에만 걸린다
  {
    id: 'focus_coffee',
    name: '집중 커피',
    description: 'Mina 가 내려준 커피. 마시면 한동안 딴생각이 안 난다.',
    type: 'CONSUMABLE',
    rarity: 'COMMON',
    icon: '☕',
    equipSlot: null,
    effectLabel: '다음 일 퀘스트 EXP +20%',
    bonuses: {},
    consumable: { category: 'WORK', expPct: 20, uses: 1 },
    giftTags: ['coffee'],
  },
  {
    id: 'rainy_day_tea',
    name: '비 오는 날의 차',
    description: '비 오는 날에만 꺼낸다는 찻잎.',
    type: 'CONSUMABLE',
    rarity: 'RARE',
    icon: '🍵',
    equipSlot: null,
    effectLabel: '다음 마음 퀘스트 EXP +20%',
    bonuses: {},
    consumable: { category: 'MIND', expPct: 20, uses: 1 },
    giftTags: ['coffee', 'cozy'],
  },
  {
    id: 'small_dessert',
    name: '작은 디저트',
    description: '한 입 크기의 케이크. 별거 아닌데 기분이 좋아진다.',
    type: 'CONSUMABLE',
    rarity: 'COMMON',
    icon: '🍰',
    equipSlot: null,
    effectLabel: '다음 퀘스트 EXP +10%',
    bonuses: {},
    consumable: { category: null, expPct: 10, uses: 1 },
    giftTags: ['cozy'],
  },

  // 장비 — 상점과 NPC 의뢰에서 나온다
  {
    id: 'morning_sneakers',
    name: '아침 운동화',
    description: 'Haru 가 신어보라며 준 운동화. 발이 가볍다.',
    type: 'EQUIPMENT',
    rarity: 'RARE',
    icon: '👟',
    equipSlot: 'SHOES',
    effectLabel: '몸 EXP +6%',
    bonuses: { expPctByCategory: { BODY: 6 } },
    giftTags: ['sport'],
  },
  {
    id: 'training_band',
    name: '운동 밴드',
    description: '어디서든 쓸 수 있는 밴드. Rio 가 하나씩 나눠준다.',
    type: 'EQUIPMENT',
    rarity: 'RARE',
    icon: '🎽',
    equipSlot: 'TOP',
    effectLabel: '몸 보상 +8%',
    bonuses: { rewardPctByCategory: { BODY: 8 } },
    giftTags: ['sport'],
  },
  {
    id: 'vintage_ribbon',
    name: '오래된 리본',
    description: 'June 의 가게에서 나온 오래된 리본. 색이 곱게 바랬다.',
    type: 'EQUIPMENT',
    rarity: 'RARE',
    icon: '🎀',
    equipSlot: 'HEAD',
    effectLabel: '놀이 EXP +5%',
    bonuses: { expPctByCategory: { PLAY: 5 } },
    giftTags: ['collectible', 'cozy'],
  },
  {
    id: 'cozy_scarf',
    name: '포근한 목도리',
    description: '목에 두르면 어깨가 저절로 내려간다.',
    type: 'EQUIPMENT',
    rarity: 'RARE',
    icon: '🧣',
    equipSlot: 'ACCESSORY',
    effectLabel: '생활 · 마음 EXP +4%',
    bonuses: { expPctByCategory: { LIFE: 4, MIND: 4 } },
    giftTags: ['cozy'],
  },
  {
    id: 'tiny_sketchbook',
    name: '작은 스케치북',
    description: '주머니에 들어가는 스케치북. Lulu 는 늘 하나씩 가지고 다닌다.',
    type: 'EQUIPMENT',
    rarity: 'RARE',
    icon: '📓',
    equipSlot: 'CHARM',
    effectLabel: '놀이 보상 +8%',
    bonuses: { rewardPctByCategory: { PLAY: 8 } },
    giftTags: ['art', 'book'],
  },
  {
    id: 'green_charm',
    name: '초록 부적',
    description: '공원에서 주운 잎으로 만든 부적.',
    type: 'EQUIPMENT',
    rarity: 'RARE',
    icon: '🍀',
    equipSlot: 'CHARM',
    effectLabel: '행운 +2 · 관계 EXP +4%',
    bonuses: { luck: 2, expPctByCategory: { HEART: 4 } },
    giftTags: ['nature'],
  },
  {
    id: 'moon_keyring',
    name: '달 키링',
    description: '달 모양 키링. 밤에 보면 아주 옅게 빛난다.',
    type: 'EQUIPMENT',
    rarity: 'EPIC',
    icon: '🌙',
    equipSlot: 'ACCESSORY',
    effectLabel: '마음 EXP +7%',
    bonuses: { expPctByCategory: { MIND: 7 } },
    giftTags: ['moon', 'collectible'],
  },
  {
    id: 'star_pin',
    name: '별 핀',
    description: 'Noa 가 준 별 모양 핀. 어디서 났는지는 안 알려줬다.',
    type: 'EQUIPMENT',
    rarity: 'EPIC',
    icon: '🌟',
    equipSlot: 'HEAD',
    effectLabel: '관계 보상 +10%',
    bonuses: { rewardPctByCategory: { HEART: 10 } },
    giftTags: ['moon', 'collectible'],
  },
  {
    id: 'night_ticket',
    name: '밤 시장 표',
    description: '밤 시장에서만 받는 표. 뭘 살 수 있는지는 그날 봐야 안다.',
    type: 'COLLECTIBLE',
    rarity: 'RARE',
    icon: '🎫',
    equipSlot: null,
    effectLabel: '아직 쓸 곳이 없다',
    bonuses: {},
    giftTags: ['moon', 'collectible'],
  },
  {
    id: 'lucky_cat_sticker',
    name: '행운 고양이 스티커',
    description: '공원 벤치에 붙어 있던 스티커. 왠지 떼기 아까웠다.',
    type: 'COLLECTIBLE',
    rarity: 'COMMON',
    icon: '🐱',
    equipSlot: null,
    effectLabel: '아직 쓸 곳이 없다',
    bonuses: {},
    giftTags: ['collectible', 'nature'],
  },
  {
    id: 'flower_bookmark',
    name: '꽃 책갈피',
    description: '말린 꽃을 끼워 만든 책갈피.',
    type: 'COLLECTIBLE',
    rarity: 'COMMON',
    icon: '🔖',
    equipSlot: null,
    effectLabel: '아직 쓸 곳이 없다',
    bonuses: {},
    giftTags: ['book', 'nature', 'art'],
  },
]

export function findItem(id: string): ItemDef | null {
  return ITEMS.find((i) => i.id === id) ?? null
}

// ── 몬스터 ──────────────────────────────────────────────
export const MONSTERS: BattleDef[] = [
  {
    id: 'dish_slime',
    kind: 'MONSTER',
    name: '설거지 슬라임',
    description: '싱크대에서 조금씩 자라는 녀석.',
    category: 'LIFE',
    icon: '🍽️',
    maxHp: 40,
    actions: [
      { label: '컵 씻기', damage: 10 },
      { label: '접시 정리', damage: 15 },
      { label: '프라이팬 씻기', damage: 15 },
    ],
    rewardExp: 40,
    rewardCoins: 60,
    guaranteedRarity: 'COMMON',
  },
  {
    id: 'laundry_blob',
    kind: 'MONSTER',
    name: '빨래 덩어리',
    description: '빨래 바구니에서 부풀어 오른 덩어리.',
    category: 'LIFE',
    icon: '🧺',
    maxHp: 60,
    actions: [
      { label: '세탁기 돌리기', damage: 20 },
      { label: '널기', damage: 20 },
      { label: '개서 넣기', damage: 20 },
    ],
    rewardExp: 60,
    rewardCoins: 90,
    guaranteedRarity: 'COMMON',
  },
  {
    id: 'mail_goblin',
    kind: 'MONSTER',
    name: '메일 고블린',
    description: '읽씹한 메일함에 사는 고블린.',
    category: 'WORK',
    icon: '✉️',
    maxHp: 50,
    actions: [
      { label: '급한 것부터 답장', damage: 25 },
      { label: '나머지 훑기', damage: 15 },
      { label: '정리·보관', damage: 10 },
    ],
    rewardExp: 50,
    rewardCoins: 75,
    guaranteedRarity: 'COMMON',
  },
  {
    id: 'task_hydra',
    kind: 'MONSTER',
    name: '할 일 히드라',
    description: '하나 끝내면 두 개가 생기는 그 일.',
    category: 'WORK',
    icon: '🐉',
    maxHp: 120,
    actions: [
      { label: '할 일 쪼개 적기', damage: 20 },
      { label: '제일 작은 것 하나', damage: 25 },
      { label: '중간 것 하나', damage: 35 },
      { label: '남은 것 마무리', damage: 40 },
    ],
    rewardExp: 120,
    rewardCoins: 180,
    guaranteedRarity: 'RARE',
  },
  {
    id: 'clutter_mimic',
    kind: 'MONSTER',
    name: '잡동사니 미믹',
    description: '열어보기 전까진 뭐가 들었는지 모르는 서랍.',
    category: 'LIFE',
    icon: '📦',
    maxHp: 100,
    actions: [
      { label: '전부 꺼내기', damage: 30 },
      { label: '버릴 것 버리기', damage: 40 },
      { label: '자리 정해 넣기', damage: 30 },
    ],
    rewardExp: 100,
    rewardCoins: 150,
    guaranteedRarity: 'RARE',
    bonusRarity: 'EPIC',
  },
]

// ── 보스 ────────────────────────────────────────────────
export const BOSSES: BattleDef[] = [
  {
    id: 'deadline_dragon',
    kind: 'BOSS',
    name: '마감 드래곤',
    description: '달력에 빨갛게 표시해둔 그날의 주인.',
    category: 'WORK',
    icon: '🔥',
    maxHp: 300,
    actions: [
      { label: '자료 조사', damage: 50 },
      { label: '초안 작성', damage: 80 },
      { label: '수정', damage: 70 },
      { label: '최종 검수', damage: 100 },
    ],
    rewardExp: 300,
    rewardCoins: 360,
    guaranteedRarity: 'RARE',
    bonusRarity: 'EPIC',
  },
  {
    id: 'cleaning_golem',
    kind: 'BOSS',
    name: '대청소 골렘',
    description: '집 전체가 한 덩어리로 뭉친 것.',
    category: 'LIFE',
    icon: '🧹',
    maxHp: 250,
    actions: [
      { label: '바닥 치우기', damage: 60 },
      { label: '먼지 닦기', damage: 60 },
      { label: '욕실', damage: 60 },
      { label: '마지막 정리', damage: 70 },
    ],
    rewardExp: 250,
    rewardCoins: 300,
    guaranteedRarity: 'RARE',
    bonusRarity: 'EPIC',
  },
  {
    id: 'monday_shadow',
    kind: 'BOSS',
    name: '월요일 그림자',
    description: '일요일 밤부터 따라오는 그림자.',
    category: 'MIND',
    icon: '🌑',
    maxHp: 180,
    actions: [
      { label: '이번 주 할 일 적기', damage: 60 },
      { label: '우선순위 정하기', damage: 60 },
      { label: '첫 한 개 시작', damage: 60 },
    ],
    rewardExp: 180,
    rewardCoins: 240,
    guaranteedRarity: 'COMMON',
    bonusRarity: 'RARE',
  },
]

export const BATTLE_DEFS = [...MONSTERS, ...BOSSES]

export function findBattleDef(id: string): BattleDef | null {
  return BATTLE_DEFS.find((b) => b.id === id) ?? null
}
