/**
 * 퀘스트 풀.
 *
 * 여기 있는 건 전부 "행동" 이다. 결과에는 XP 를 주지 않는다 —
 * 체중이 얼마나 줄었는지, 얼마나 적게 먹었는지, 얼마나 세게 운동했는지는
 * 퀘스트가 되지 않는다. 적고, 챙기고, 나를 돌보는 일만 퀘스트가 된다.
 *
 * 이 파일은 DB 가 아니라 코드에 둔다. 마이그레이션 없이 고칠 수 있고,
 * 오프라인에서도 그대로 뜨고, 검색·추천이 전부 로컬에서 끝나기 때문이다.
 * 사용자가 만든 퀘스트만 DB(custom_quests)에 저장한다.
 */
import type { Quest } from './types'

export const QUEST_POOL: Quest[] = [
  // ── care
  { id: 'water', title: '물 한 잔 마시기', category: 'care', difficulty: 'tiny', repeatable: true, dailyXpLimit: 4, modes: ['RECOVERY', 'EASY'] },
  { id: 'fill-bottle', title: '물병 채워 두기', category: 'care', difficulty: 'tiny', modes: ['RECOVERY', 'EASY'] },
  { id: 'wash-face', title: '세수하기', category: 'care', difficulty: 'tiny', modes: ['RECOVERY', 'EASY'] },
  { id: 'brush-teeth', title: '양치하기', category: 'care', difficulty: 'tiny', repeatable: true, dailyXpLimit: 2, modes: ['RECOVERY', 'EASY'] },
  { id: 'shower', title: '샤워하기', category: 'care', difficulty: 'easy', modes: ['RECOVERY', 'EASY'] },
  { id: 'wash-hair', title: '머리 감기', category: 'care', difficulty: 'easy', modes: ['RECOVERY', 'EASY'] },
  { id: 'skincare', title: '스킨케어 하기', category: 'care', difficulty: 'tiny', modes: ['RECOVERY', 'EASY'] },
  { id: 'lipbalm', title: '립밤 바르기', category: 'care', difficulty: 'tiny', modes: ['RECOVERY', 'EASY'] },
  { id: 'nails', title: '손톱 정리하기', category: 'care', difficulty: 'easy', modes: ['RECOVERY', 'EASY'] },
  { id: 'change-clothes', title: '편한 옷으로 갈아입기', category: 'care', difficulty: 'tiny', modes: ['RECOVERY', 'EASY'] },
  { id: 'make-bed', title: '침구 정리하기', category: 'care', difficulty: 'tiny', modes: ['RECOVERY', 'EASY'] },
  { id: 'open-window', title: '창문 열기', category: 'care', difficulty: 'tiny', modes: ['RECOVERY', 'EASY'] },
  { id: 'air-out', title: '5분 환기하기', category: 'care', difficulty: 'tiny', modes: ['RECOVERY', 'EASY'] },
  { id: 'sunlight', title: '햇빛 잠깐 보기', category: 'care', difficulty: 'tiny', modes: ['RECOVERY', 'EASY'] },
  { id: 'hand-cream', title: '핸드크림 바르기', category: 'care', difficulty: 'tiny', modes: ['RECOVERY', 'EASY'] },
  { id: 'eye-rest', title: '눈 감고 1분 쉬기', category: 'care', difficulty: 'tiny', repeatable: true, dailyXpLimit: 3, modes: ['RECOVERY', 'EASY'] },
  { id: 'take-vitamin', title: '챙겨 먹기로 한 것 챙기기', category: 'care', difficulty: 'tiny', modes: ['RECOVERY', 'EASY'] },
  // ── food
  { id: 'a-meal', title: '뭐라도 한 끼 챙기기', category: 'food', difficulty: 'easy', repeatable: true, dailyXpLimit: 3 },
  { id: 'protein', title: '단백질 있는 음식 먹기', category: 'food', difficulty: 'easy' },
  { id: 'fruit', title: '과일 하나 먹기', category: 'food', difficulty: 'tiny' },
  { id: 'veggie', title: '채소 조금 더하기', category: 'food', difficulty: 'tiny' },
  { id: 'warm-food', title: '따뜻한 음식 먹기', category: 'food', difficulty: 'easy' },
  { id: 'eat-slow', title: '천천히 먹어 보기', category: 'food', difficulty: 'easy' },
  { id: 'phone-down-meal', title: '밥 먹을 때 휴대폰 내려놓기', category: 'food', difficulty: 'easy' },
  { id: 'log-food', title: '오늘 먹은 것 기록하기', category: 'food', difficulty: 'tiny' },
  { id: 'water-with-meal', title: '물이랑 같이 먹기', category: 'food', difficulty: 'tiny' },
  { id: 'prep-tomorrow', title: '내일 먹을 것 하나 준비하기', category: 'food', difficulty: 'normal' },
  { id: 'warm-drink', title: '따뜻한 거 한 잔', category: 'food', difficulty: 'tiny', repeatable: true, dailyXpLimit: 3 },
  { id: 'snack-plate', title: '간식 접시에 덜어 먹기', category: 'food', difficulty: 'tiny' },
  { id: 'try-new-food', title: '안 먹어본 것 하나 시도', category: 'food', difficulty: 'normal' },
  { id: 'grocery', title: '장 볼 것 하나 적어두기', category: 'food', difficulty: 'tiny' },
  // ── home
  { id: 'floor-3', title: '바닥에 있는 것 3개 치우기', category: 'home', difficulty: 'tiny', repeatable: true, dailyXpLimit: 3, events: ['집콕', '재택', '휴일'] },
  { id: 'desk-zone', title: '책상 한 구역 정리', category: 'home', difficulty: 'easy', events: ['집콕', '재택', '휴일'] },
  { id: 'one-trash', title: '쓰레기 하나 버리기', category: 'home', difficulty: 'tiny', repeatable: true, dailyXpLimit: 3, events: ['집콕', '재택', '휴일'] },
  { id: 'cup-away', title: '컵 가져다 놓기', category: 'home', difficulty: 'tiny', repeatable: true, dailyXpLimit: 3, events: ['집콕', '재택', '휴일'] },
  { id: 'dishes-3', title: '설거지 3개만 하기', category: 'home', difficulty: 'tiny', events: ['집콕', '재택', '휴일'] },
  { id: 'gather-laundry', title: '빨래 모으기', category: 'home', difficulty: 'tiny', events: ['집콕', '재택', '휴일'] },
  { id: 'run-laundry', title: '빨래 돌리기', category: 'home', difficulty: 'easy', events: ['집콕', '재택', '휴일'] },
  { id: 'fold-laundry', title: '빨래 개기', category: 'home', difficulty: 'normal', events: ['집콕', '재택', '휴일'] },
  { id: 'tidy-bed', title: '침대 정리', category: 'home', difficulty: 'tiny', events: ['집콕', '재택', '휴일'] },
  { id: 'tidy-5', title: '5분만 치우기', category: 'home', difficulty: 'easy', repeatable: true, dailyXpLimit: 2, events: ['집콕', '재택', '휴일'] },
  { id: 'tidy-15', title: '15분 청소', category: 'home', difficulty: 'normal', events: ['집콕', '재택', '휴일'] },
  { id: 'vanity', title: '화장대 정리', category: 'home', difficulty: 'normal', events: ['집콕', '재택', '휴일'] },
  { id: 'bag-clean', title: '가방 정리', category: 'home', difficulty: 'easy', events: ['집콕', '재택', '휴일'] },
  { id: 'one-clothes', title: '옷 하나 제자리에', category: 'home', difficulty: 'tiny', repeatable: true, dailyXpLimit: 3, events: ['집콕', '재택', '휴일'] },
  { id: 'box-out', title: '택배 박스 버리기', category: 'home', difficulty: 'tiny', events: ['집콕', '재택', '휴일'] },
  { id: 'fridge-shelf', title: '냉장고 한 칸 정리', category: 'home', difficulty: 'normal', events: ['집콕', '재택', '휴일'] },
  { id: 'bathroom-spot', title: '욕실 한 곳 닦기', category: 'home', difficulty: 'easy', events: ['집콕', '재택', '휴일'] },
  { id: 'water-plant', title: '화분에 물 주기', category: 'home', difficulty: 'tiny', events: ['집콕', '재택', '휴일'] },
  { id: 'change-sheets', title: '침구 갈기', category: 'home', difficulty: 'big', events: ['집콕', '재택', '휴일'] },
  { id: 'shoe-rack', title: '신발장 정리', category: 'home', difficulty: 'normal', events: ['집콕', '재택', '휴일'] },
  // ── mind
  { id: 'mood-word', title: '오늘 기분 한 단어로 적기', category: 'mind', difficulty: 'tiny' },
  { id: 'want-now', title: '지금 하고 싶은 것 적기', category: 'mind', difficulty: 'tiny' },
  { id: 'one-good', title: '오늘 좋았던 것 하나 찾기', category: 'mind', difficulty: 'tiny' },
  { id: 'one-hard', title: '오늘 힘든 것 한 줄 쓰기', category: 'mind', difficulty: 'tiny' },
  { id: 'nothing-5', title: '아무것도 안 하고 5분 쉬기', category: 'mind', difficulty: 'easy' },
  { id: 'one-song', title: '좋아하는 음악 한 곡 듣기', category: 'mind', difficulty: 'tiny' },
  { id: 'look-outside', title: '창밖 보기', category: 'mind', difficulty: 'tiny' },
  { id: 'photo-scroll', title: '사진첩 잠깐 보기', category: 'mind', difficulty: 'tiny' },
  { id: 'did-well', title: '내가 잘한 것 하나 기록', category: 'mind', difficulty: 'tiny' },
  { id: 'park-worry', title: '내일 걱정 하나 적어두기', category: 'mind', difficulty: 'tiny' },
  { id: 'deep-breath', title: '크게 숨 세 번 쉬기', category: 'mind', difficulty: 'tiny', repeatable: true, dailyXpLimit: 3 },
  { id: 'thank-one', title: '고마운 것 하나 적기', category: 'mind', difficulty: 'tiny' },
  { id: 'say-no', title: '오늘 하나는 안 하기로 정하기', category: 'mind', difficulty: 'easy' },
  { id: 'brain-dump', title: '머릿속에 있는 거 다 적어보기', category: 'mind', difficulty: 'normal' },
  { id: 'mood-check', title: '지금 기분 점수 매겨보기', category: 'mind', difficulty: 'tiny' },
  // ── work
  { id: 'smallest-task', title: '가장 작은 업무 하나 끝내기', category: 'work', difficulty: 'easy', modes: ['NORMAL', 'POWER'] },
  { id: 'one-file', title: '미뤄둔 파일 하나 정리', category: 'work', difficulty: 'easy', modes: ['NORMAL', 'POWER'] },
  { id: 'one-mail', title: '메일 하나 처리', category: 'work', difficulty: 'tiny', repeatable: true, dailyXpLimit: 3, modes: ['NORMAL', 'POWER'] },
  { id: 'focus-10', title: '10분 집중', category: 'work', difficulty: 'easy', modes: ['NORMAL', 'POWER'] },
  { id: 'focus-25', title: '25분 집중', category: 'work', difficulty: 'normal', repeatable: true, dailyXpLimit: 3, modes: ['NORMAL', 'POWER'] },
  { id: 'todo-3', title: '오늘 할 일 3개 적기', category: 'work', difficulty: 'tiny', modes: ['NORMAL', 'POWER'] },
  { id: 'check-done', title: '업무 하나 완료 체크', category: 'work', difficulty: 'tiny', repeatable: true, dailyXpLimit: 3, modes: ['NORMAL', 'POWER'] },
  { id: 'folder-tidy', title: '폴더 정리', category: 'work', difficulty: 'easy', modes: ['NORMAL', 'POWER'] },
  { id: 'downloads', title: '다운로드 폴더 정리', category: 'work', difficulty: 'easy', modes: ['NORMAL', 'POWER'] },
  { id: 'screenshots', title: '스크린샷 정리', category: 'work', difficulty: 'easy', modes: ['NORMAL', 'POWER'] },
  { id: 'idea-note', title: '아이디어 하나 메모', category: 'work', difficulty: 'tiny', modes: ['NORMAL', 'POWER'] },
  { id: 'delegate-ai', title: '귀찮은 일 하나 AI 에게 맡기기', category: 'work', difficulty: 'easy', modes: ['NORMAL', 'POWER'] },
  { id: 'first-tomorrow', title: '내일 첫 업무 정하기', category: 'work', difficulty: 'tiny', modes: ['NORMAL', 'POWER'] },
  { id: 'close-tabs', title: '탭 정리하기', category: 'work', difficulty: 'tiny', modes: ['NORMAL', 'POWER'] },
  { id: 'inbox-zero-ish', title: '읽지 않은 알림 정리', category: 'work', difficulty: 'easy', modes: ['NORMAL', 'POWER'] },
  { id: 'stand-up', title: '일하다 한 번 일어나기', category: 'work', difficulty: 'tiny', repeatable: true, dailyXpLimit: 4, modes: ['NORMAL', 'POWER'] },
  // ── style
  { id: 'save-look', title: '오늘 룩 저장', category: 'style', difficulty: 'tiny' },
  { id: 'ootd', title: 'OOTD 사진 찍기', category: 'style', difficulty: 'tiny' },
  { id: 'fav-clothes', title: '좋아하는 옷 입기', category: 'style', difficulty: 'tiny' },
  { id: 'unused-clothes', title: '안 입던 옷 하나 꺼내보기', category: 'style', difficulty: 'easy' },
  { id: 'accessory', title: '액세서리 하나 더하기', category: 'style', difficulty: 'tiny' },
  { id: 'change-bag', title: '가방 바꿔보기', category: 'style', difficulty: 'tiny' },
  { id: 'plan-outfit', title: '내일 옷 미리 정하기', category: 'style', difficulty: 'easy' },
  { id: 'wishlist', title: '위시 아이템 하나 정리', category: 'style', difficulty: 'tiny' },
  { id: 'closet-photo', title: '옷장 사진 하나 추가', category: 'style', difficulty: 'tiny' },
  { id: 'style-point', title: '오늘 마음에 든 포인트 기록', category: 'style', difficulty: 'tiny' },
  { id: 'try-combo', title: '안 해본 조합 하나 입어보기', category: 'style', difficulty: 'easy' },
  { id: 'mirror-check', title: '거울 앞에서 한 번 웃기', category: 'style', difficulty: 'tiny' },
  // ── love
  { id: 'send-heart', title: '{partner}에게 하트 보내기', category: 'love', difficulty: 'tiny', events: ['데이트'] },
  { id: 'say-thanks', title: '고맙다고 한마디 하기', category: 'love', difficulty: 'tiny', events: ['데이트'] },
  { id: 'cute-photo', title: '귀여운 사진 보내기', category: 'love', difficulty: 'tiny', events: ['데이트'] },
  { id: 'share-day', title: '오늘 있었던 일 하나 공유', category: 'love', difficulty: 'tiny', events: ['데이트'] },
  { id: 'compliment', title: '칭찬 하나 하기', category: 'love', difficulty: 'tiny', events: ['데이트'] },
  { id: 'save-todo-together', title: '같이 하고 싶은 것 하나 저장', category: 'love', difficulty: 'tiny', events: ['데이트'] },
  { id: 'date-idea', title: '데이트 아이디어 하나 추가', category: 'love', difficulty: 'tiny', events: ['데이트'] },
  { id: 'look-memory', title: '추억 사진 하나 보기', category: 'love', difficulty: 'tiny', events: ['데이트'] },
  { id: 'good-morning', title: '먼저 안부 묻기', category: 'love', difficulty: 'tiny', events: ['데이트'] },
  { id: 'plan-together', title: '다음에 만날 날 얘기하기', category: 'love', difficulty: 'easy', events: ['데이트'] },
  { id: 'small-gift', title: '작은 선물 하나 생각해두기', category: 'love', difficulty: 'easy', events: ['데이트'] },
  { id: 'log-together', title: '함께한 날 기록하기', category: 'love', difficulty: 'tiny', events: ['데이트'] },
  // ── social
  { id: 'reply-message', title: '밀린 답장 하나 보내기', category: 'social', difficulty: 'tiny', repeatable: true, dailyXpLimit: 3 },
  { id: 'call-family', title: '가족에게 연락하기', category: 'social', difficulty: 'easy' },
  { id: 'friend-hi', title: '친구에게 안부 보내기', category: 'social', difficulty: 'tiny' },
  { id: 'make-plan', title: '약속 하나 잡기', category: 'social', difficulty: 'easy' },
  { id: 'congrats', title: '축하할 일 하나 축하하기', category: 'social', difficulty: 'tiny' },
  { id: 'share-link', title: '좋았던 것 하나 공유하기', category: 'social', difficulty: 'tiny' },
  { id: 'alone-time', title: '혼자 있는 시간 챙기기', category: 'social', difficulty: 'easy' },
  { id: 'decline-kindly', title: '부담되는 약속 정리하기', category: 'social', difficulty: 'easy' },
  // ── fun
  { id: 'game-10', title: '게임 10분 하기', category: 'fun', difficulty: 'easy' },
  { id: 'fun-video', title: '재밌는 영상 하나 보기', category: 'fun', difficulty: 'tiny' },
  { id: 'fav-song', title: '좋아하는 노래 듣기', category: 'fun', difficulty: 'tiny' },
  { id: 'take-photo', title: '사진 찍기', category: 'fun', difficulty: 'tiny', repeatable: true, dailyXpLimit: 3 },
  { id: 'draw', title: '그림 그리기', category: 'fun', difficulty: 'easy' },
  { id: 'ai-image', title: 'AI 이미지 하나 만들기', category: 'fun', difficulty: 'easy' },
  { id: 'new-idea', title: '새 아이디어 하나 만들기', category: 'fun', difficulty: 'easy' },
  { id: 'silly-thing', title: '쓸데없이 재밌는 것 해보기', category: 'fun', difficulty: 'tiny' },
  { id: 'hobby-10', title: '취미 10분', category: 'fun', difficulty: 'easy' },
  { id: 'window-shop', title: '갖고 싶은 것 구경하기', category: 'fun', difficulty: 'tiny' },
  { id: 'playlist', title: '플레이리스트 하나 만들기', category: 'fun', difficulty: 'normal' },
  { id: 'rewatch', title: '좋아하는 거 다시 보기', category: 'fun', difficulty: 'easy' },
  // ── growth
  { id: 'read-page', title: '책 한 쪽 읽기', category: 'growth', difficulty: 'tiny', modes: ['NORMAL', 'POWER'] },
  { id: 'read-10', title: '10분 읽기', category: 'growth', difficulty: 'easy', modes: ['NORMAL', 'POWER'] },
  { id: 'learn-word', title: '새 단어 하나 배우기', category: 'growth', difficulty: 'tiny', modes: ['NORMAL', 'POWER'] },
  { id: 'watch-lesson', title: '배우는 영상 하나 보기', category: 'growth', difficulty: 'normal', modes: ['NORMAL', 'POWER'] },
  { id: 'note-learned', title: '오늘 배운 것 한 줄 적기', category: 'growth', difficulty: 'tiny', modes: ['NORMAL', 'POWER'] },
  { id: 'try-tool', title: '새 도구 하나 써보기', category: 'growth', difficulty: 'normal', modes: ['NORMAL', 'POWER'] },
  { id: 'review-goal', title: '목표 한 번 다시 보기', category: 'growth', difficulty: 'easy', modes: ['NORMAL', 'POWER'] },
  { id: 'save-reference', title: '참고할 것 하나 저장', category: 'growth', difficulty: 'tiny', modes: ['NORMAL', 'POWER'] },
  { id: 'practice-15', title: '연습 15분', category: 'growth', difficulty: 'normal', modes: ['NORMAL', 'POWER'] },
  { id: 'teach-one', title: '아는 것 하나 설명해보기', category: 'growth', difficulty: 'easy', modes: ['NORMAL', 'POWER'] },
  // ── move
  { id: 'walk-inside-3', title: '집 안에서 3분 걷기', category: 'move', difficulty: 'tiny', repeatable: true, dailyXpLimit: 3, modes: ['NORMAL', 'POWER'] },
  { id: 'walk-5', title: '5분 걷기', category: 'move', difficulty: 'tiny', repeatable: true, dailyXpLimit: 3, modes: ['NORMAL', 'POWER'] },
  { id: 'walk-10', title: '10분 걷기', category: 'move', difficulty: 'easy', modes: ['NORMAL', 'POWER'] },
  { id: 'walk-20', title: '20분 걷기', category: 'move', difficulty: 'normal', modes: ['NORMAL', 'POWER'] },
  { id: 'loosen-up', title: '가볍게 몸 풀기', category: 'move', difficulty: 'tiny', modes: ['NORMAL', 'POWER'] },
  { id: 'neck-roll', title: '목 천천히 돌리기', category: 'move', difficulty: 'tiny', repeatable: true, dailyXpLimit: 3, modes: ['NORMAL', 'POWER'] },
  { id: 'shoulder', title: '어깨 풀기', category: 'move', difficulty: 'tiny', repeatable: true, dailyXpLimit: 3, modes: ['NORMAL', 'POWER'] },
  { id: 'wrist', title: '손목 스트레칭', category: 'move', difficulty: 'tiny', repeatable: true, dailyXpLimit: 3, modes: ['NORMAL', 'POWER'] },
  { id: 'step-outside', title: '밖에 잠깐 나가기', category: 'move', difficulty: 'tiny', modes: ['NORMAL', 'POWER'] },
  { id: 'stretch-back', title: '허리 편하게 늘리기', category: 'move', difficulty: 'tiny', modes: ['NORMAL', 'POWER'] },
  { id: 'dance-one', title: '노래 한 곡 만큼 움직이기', category: 'move', difficulty: 'easy', modes: ['NORMAL', 'POWER'] },
  { id: 'walk-errand', title: '걸어서 볼일 하나 보기', category: 'move', difficulty: 'normal', modes: ['NORMAL', 'POWER'] },
  // ── climbing
  { id: 'pack-bag', title: '클라이밍 가방 챙기기', category: 'climbing', difficulty: 'tiny', modes: ['NORMAL', 'POWER'], events: ['클라이밍'] },
  { id: 'pack-shoes', title: '암벽화 챙기기', category: 'climbing', difficulty: 'tiny', modes: ['NORMAL', 'POWER'], events: ['클라이밍'] },
  { id: 'check-chalk', title: '초크 확인', category: 'climbing', difficulty: 'tiny', modes: ['NORMAL', 'POWER'], events: ['클라이밍'] },
  { id: 'warmup', title: '워밍업 충분히 하기', category: 'climbing', difficulty: 'easy', modes: ['NORMAL', 'POWER'], events: ['클라이밍'] },
  { id: 'easy-first', title: '쉬운 문제로 몸 풀기', category: 'climbing', difficulty: 'easy', modes: ['NORMAL', 'POWER'], events: ['클라이밍'] },
  { id: 'log-fun-problem', title: '오늘 재밌던 문제 기록', category: 'climbing', difficulty: 'tiny', modes: ['NORMAL', 'POWER'], events: ['클라이밍'] },
  { id: 'log-move', title: '좋았던 무브 하나 기록', category: 'climbing', difficulty: 'tiny', modes: ['NORMAL', 'POWER'], events: ['클라이밍'] },
  { id: 'stop-early', title: '무리하지 않고 끝내기', category: 'climbing', difficulty: 'easy', modes: ['NORMAL', 'POWER'], events: ['클라이밍'] },
  { id: 'water-after', title: '운동 후 물 챙기기', category: 'climbing', difficulty: 'tiny', modes: ['NORMAL', 'POWER'], events: ['클라이밍'] },
  { id: 'climb-log', title: '클라이밍 로그 남기기', category: 'climbing', difficulty: 'tiny', modes: ['NORMAL', 'POWER'], events: ['클라이밍'] },
  { id: 'stretch-after', title: '끝나고 스트레칭', category: 'climbing', difficulty: 'easy', modes: ['NORMAL', 'POWER'], events: ['클라이밍'] },
  { id: 'gym-plan', title: '다음에 갈 날 정하기', category: 'climbing', difficulty: 'tiny', modes: ['NORMAL', 'POWER'], events: ['클라이밍'] },
  // ── recovery
  { id: 'lie-10', title: '10분 누워 있기', category: 'recovery', difficulty: 'easy', modes: ['RECOVERY'], events: ['야근', '바쁜 날', '피곤함', '근육통'] },
  { id: 'warm-water', title: '따뜻한 물 마시기', category: 'recovery', difficulty: 'tiny', repeatable: true, dailyXpLimit: 3, modes: ['RECOVERY'], events: ['야근', '바쁜 날', '피곤함', '근육통'] },
  { id: 'wash-early', title: '일찍 씻기', category: 'recovery', difficulty: 'easy', modes: ['RECOVERY'], events: ['야근', '바쁜 날', '피곤함', '근육통'] },
  { id: 'dim-light', title: '조명 낮추기', category: 'recovery', difficulty: 'tiny', modes: ['RECOVERY'], events: ['야근', '바쁜 날', '피곤함', '근육통'] },
  { id: 'phone-away', title: '휴대폰 잠깐 내려놓기', category: 'recovery', difficulty: 'easy', modes: ['RECOVERY'], events: ['야근', '바쁜 날', '피곤함', '근육통'] },
  { id: 'comfy-clothes', title: '편한 옷 입기', category: 'recovery', difficulty: 'tiny', modes: ['RECOVERY'], events: ['야근', '바쁜 날', '피곤함', '근육통'] },
  { id: 'prep-bed', title: '침대 준비하기', category: 'recovery', difficulty: 'tiny', modes: ['RECOVERY'], events: ['야근', '바쁜 날', '피곤함', '근육통'] },
  { id: 'set-alarm', title: '알람 맞추기', category: 'recovery', difficulty: 'tiny', modes: ['RECOVERY'], events: ['야근', '바쁜 날', '피곤함', '근육통'] },
  { id: 'drop-tomorrow', title: '내일 할 일 내려놓기', category: 'recovery', difficulty: 'tiny', modes: ['RECOVERY'], events: ['야근', '바쁜 날', '피곤함', '근육통'] },
  { id: 'declare-done', title: '오늘은 여기까지 선언하기', category: 'recovery', difficulty: 'tiny', modes: ['RECOVERY'], events: ['야근', '바쁜 날', '피곤함', '근육통'] },
  { id: 'lie-early', title: '일찍 눕기', category: 'recovery', difficulty: 'easy', modes: ['RECOVERY'], events: ['야근', '바쁜 날', '피곤함', '근육통'] },
  { id: 'warm-shower', title: '따뜻하게 씻기', category: 'recovery', difficulty: 'easy', modes: ['RECOVERY'], events: ['야근', '바쁜 날', '피곤함', '근육통'] },
  { id: 'no-screen-bed', title: '침대에서 화면 안 보기', category: 'recovery', difficulty: 'easy', modes: ['RECOVERY'], events: ['야근', '바쁜 날', '피곤함', '근육통'] },
  { id: 'slow-night', title: '밤에 천천히 움직이기', category: 'recovery', difficulty: 'tiny', modes: ['RECOVERY'], events: ['야근', '바쁜 날', '피곤함', '근육통'] },
  // ── life
  { id: 'one-errand', title: '미뤄둔 볼일 하나 처리', category: 'life', difficulty: 'normal' },
  { id: 'pay-one', title: '내야 할 것 하나 내기', category: 'life', difficulty: 'easy' },
  { id: 'book-appt', title: '예약 하나 잡기', category: 'life', difficulty: 'easy' },
  { id: 'check-calendar', title: '달력 한 번 보기', category: 'life', difficulty: 'tiny' },
  { id: 'charge-things', title: '충전해둘 것 챙기기', category: 'life', difficulty: 'tiny' },
  { id: 'backup-photos', title: '사진 백업하기', category: 'life', difficulty: 'normal' },
  { id: 'wallet-tidy', title: '지갑 정리', category: 'life', difficulty: 'easy' },
  { id: 'unsubscribe', title: '안 보는 구독 하나 정리', category: 'life', difficulty: 'easy' },
  { id: 'weigh-in', title: '체중 재고 기록하기', category: 'life', difficulty: 'tiny' },
  { id: 'log-injection', title: '투약 기록 남기기', category: 'life', difficulty: 'tiny' },
  { id: 'plan-week', title: '이번 주 하나 정하기', category: 'life', difficulty: 'easy' },
  { id: 'fix-small', title: '고장난 것 하나 손보기', category: 'life', difficulty: 'normal' },
  // ── memory
  { id: 'save-photo', title: '오늘 사진 한 장 저장', category: 'memory', difficulty: 'tiny', events: ['데이트', '새로운 장소', '좋은 일'] },
  { id: 'one-line', title: '오늘의 한 줄 기록', category: 'memory', difficulty: 'tiny', events: ['데이트', '새로운 장소', '좋은 일'] },
  { id: 'laugh-log', title: '오늘 웃었던 일 기록', category: 'memory', difficulty: 'tiny', events: ['데이트', '새로운 장소', '좋은 일'] },
  { id: 'food-photo', title: '오늘 먹은 것 사진', category: 'memory', difficulty: 'tiny', events: ['데이트', '새로운 장소', '좋은 일'] },
  { id: 'look-photo', title: '오늘 룩 사진', category: 'memory', difficulty: 'tiny', events: ['데이트', '새로운 장소', '좋은 일'] },
  { id: 'sky-photo', title: '오늘 하늘 사진', category: 'memory', difficulty: 'tiny', events: ['데이트', '새로운 장소', '좋은 일'] },
  { id: 'save-liked', title: '오늘 마음에 든 것 저장', category: 'memory', difficulty: 'tiny', events: ['데이트', '새로운 장소', '좋은 일'] },
  { id: 'moment-with', title: '{partner}와의 작은 순간 기록', category: 'memory', difficulty: 'tiny', events: ['데이트', '새로운 장소', '좋은 일'] },
  { id: 'song-of-day', title: '오늘의 노래 저장', category: 'memory', difficulty: 'tiny', events: ['데이트', '새로운 장소', '좋은 일'] },
  { id: 'place-of-day', title: '오늘의 장소 저장', category: 'memory', difficulty: 'tiny', events: ['데이트', '새로운 장소', '좋은 일'] },
  { id: 'week-photo', title: '이번 주 사진 하나 고르기', category: 'memory', difficulty: 'easy', events: ['데이트', '새로운 장소', '좋은 일'] },
  // ── cozy
  { id: 'cat-time', title: '고양이랑 놀아주기', category: 'cozy', difficulty: 'tiny', modes: ['RECOVERY', 'EASY'] },
  { id: 'blanket', title: '담요 덮기', category: 'cozy', difficulty: 'tiny', modes: ['RECOVERY', 'EASY'] },
  { id: 'candle', title: '초 켜기', category: 'cozy', difficulty: 'tiny', modes: ['RECOVERY', 'EASY'] },
  { id: 'warm-light', title: '따뜻한 불빛 켜기', category: 'cozy', difficulty: 'tiny', modes: ['RECOVERY', 'EASY'] },
  { id: 'slow-tea', title: '차 천천히 마시기', category: 'cozy', difficulty: 'easy', modes: ['RECOVERY', 'EASY'] },
  { id: 'cozy-corner', title: '좋아하는 자리에 앉기', category: 'cozy', difficulty: 'tiny', modes: ['RECOVERY', 'EASY'] },
  { id: 'soft-music', title: '잔잔한 음악 틀기', category: 'cozy', difficulty: 'tiny', modes: ['RECOVERY', 'EASY'] },
  { id: 'nothing-nice', title: '창가에서 멍 때리기', category: 'cozy', difficulty: 'tiny', modes: ['RECOVERY', 'EASY'] },
  { id: 'bath', title: '반신욕 하기', category: 'cozy', difficulty: 'normal', modes: ['RECOVERY', 'EASY'] },
  { id: 'pet-photo', title: '고양이 사진 찍기', category: 'cozy', difficulty: 'tiny', modes: ['RECOVERY', 'EASY'] },
]

/** id → 퀘스트 */
export const QUEST_BY_ID: Record<string, Quest> = Object.fromEntries(
  QUEST_POOL.map((q) => [q.id, q]),
)
